from django.conf.urls import url

from psct.views import pontuacao as views

urlpatterns = [
    url(
        r"^pontuacao/inscricao/insert/(?P<fase_pk>[\d]+)/(?P<inscricao_pk>[\d]+)/$",
        views.AddInscricaoPilhaView.as_view(),
        name="add_pilha_pontuacao_psct",
    ),
    url(
        "^pontuacao/inscricao/$",
        views.ListInscricaoPontuacaoView.as_view(),
        name="list_pontuacao_inscricao_psct",
    ),
    url(
        r"^pontuacao/lote/avaliador/(?P<fase_pk>[\d]+)/(?P<quantidade>[\d]+)/$",
        views.CreateLoteAvaliadorPontuacaoView.as_view(),
        name="add_lote_avaliador_pontuacao_psct",
    ),
    url(
        r"^pontuacao/lote/homologador/(?P<fase_pk>[\d]+)/(?P<quantidade>[\d]+)/$",
        views.CreateLoteHomologadorPontuacaoView.as_view(),
        name="add_lote_homologador_pontuacao_psct",
    ),
    url(
        "^pontuacao/redistribuir/avaliador/(?P<fase_pk>[0-9]+)/$",
        views.RedistribuirPontuacaoAvaliadorView.as_view(),
        name="redistribuir_pontuacao_avaliador_psct",
    ),
    url(
        "^pontuacao/redistribuir/homologador/(?P<fase_pk>[0-9]+)/$",
        views.RedistribuirPontuacaoHomologadorView.as_view(),
        name="redistribuir_pontuacao_homologador_psct",
    ),
    url(
        r"^pontuacao/(?P<fase_pk>[\d]+)/(?P<inscricao_pk>[\d]+)/avaliador/add/$",
        views.CreatePontuacaoAvaliadorView.as_view(),
        name="add_pontuacao_avaliador_psct",
    ),
    url(
        r"^pontuacao/(?P<pk>[\d]+)/avaliador/change/$",
        views.UpdatePontuacaoAvaliadorView.as_view(),
        name="change_pontuacao_avaliador_psct",
    ),
    url(
        r"^pontuacao/avaliador/(?P<pk>[\d]+)/$",
        views.PontuacaoAvaliadorView.as_view(),
        name="view_pontuacao_avaliador_psct",
    ),
    url(
        r"^pontuacao/(?P<fase_pk>[\d]+)/(?P<inscricao_pk>[\d]+)/homologador/add/$",
        views.CreatePontuacaoHomologadorView.as_view(),
        name="add_pontuacao_homologador_psct",
    ),
    url(
        r"^pontuacao/(?P<pk>[\d]+)/homologador/change/$",
        views.UpdatePontuacaoHomologadorView.as_view(),
        name="change_pontuacao_homologador_psct",
    ),
    url(
        r"^pontuacao/homologador/(?P<pk>[\d]+)/$",
        views.PontuacaoHomologadorView.as_view(),
        name="view_pontuacao_homologador_psct",
    ),
    url(
        r"^pontuacao/adminview/(?P<pk>[\d]+)/$",
        views.PontuacaoAdminView.as_view(),
        name="view_pontuacao_inscricao_psct",
    ),
    url(
        r"^pontuacao/avaliador/devolver/(?P<mailbox_pk>[\d]+)/(?P<inscricao_pk>[\d]+)/$",
        views.DevolverInscricaoAvaliadorView.as_view(),
        name="devolver_pontuacao_avaliador_psct",
    ),
    url(
        r"^pontuacao/homologador/devolver/(?P<mailbox_pk>[\d]+)/(?P<inscricao_pk>[\d]+)/$",
        views.DevolverInscricaoHomologadorView.as_view(),
        name="devolver_pontuacao_homologador_psct",
    ),
    url(
        r"^pontuacao/importar/(?P<fase_pk>[\d]+)/$",
        views.ImportarInscricaoView.as_view(),
        name="importar_inscricao_pontuacao_psct",
    ),
]
