from django.conf.urls import url

from psct.views import recurso as views

urlpatterns = [
    url(
        "^recurso/(?P<fase_pk>[0-9]+)/add/$",
        views.RecursoCreateView.as_view(),
        name="add_recurso_psct",
    ),
    url(
        "^recurso/(?P<pk>[0-9]+)/change/$",
        views.RecursoUpdateView.as_view(),
        name="change_recurso_psct",
    ),
    url(
        "^recurso/(?P<edital_pk>[0-9]+)/grupo/add/$",
        views.GrupoCreateView.as_view(),
        name="add_grupo_recurso_psct",
    ),
    url(
        "^recurso/grupo/(?P<grupoedital_pk>[0-9]+)/change/$",
        views.GrupoUpdateView.as_view(),
        name="change_grupo_recurso_psct",
    ),
    url(
        "^recurso/(?P<fase_pk>[0-9]+)/agrupar/$",
        views.AgruparRecursoView.as_view(),
        name="agrupar_recurso_psct",
    ),
    url(
        "^recurso/(?P<fase_pk>[0-9]+)/(?P<coluna_pk>[0-9]+)/distribuir/$",
        views.DistribuirRecursoView.as_view(),
        name="distribuir_recurso_psct",
    ),
    url(
        "^recurso/(?P<pk>[0-9]+)/admin_view/$",
        views.RecursoAdminView.as_view(),
        name="adminview_recurso_psct",
    ),
    url(
        "^recurso/(?P<pk>[0-9]+)/parecer_avaliador/add/$",
        views.CreateParecerAvaliadorView.as_view(),
        name="add_parecer_avaliador_psct",
    ),
    url(
        "^recurso/parecer_avaliador/(?P<pk>[0-9]+)/change/$",
        views.UpdateParecerAvaliadorView.as_view(),
        name="change_parecer_avaliador_psct",
    ),
    url(
        "^recurso/(?P<pk>[0-9]+)/parecer_homologador/add/$",
        views.CreateParecerHomologadorView.as_view(),
        name="add_parecer_homologador_psct",
    ),
    url(
        "^recurso/parecer_homologador/(?P<pk>[0-9]+)/change/$",
        views.UpdateParecerHomologadorView.as_view(),
        name="change_parecer_homologador_psct",
    ),
    url("^recurso/$", views.ListRecursoView.as_view(), name="list_recurso_psct"),
    url(
        "^recurso/(?P<pk>[0-9]+)/$",
        views.RecursoView.as_view(),
        name="view_recurso_psct",
    ),
    url(
        "^recurso/parecer_avaliador/(?P<pk>[0-9]+)/$",
        views.ParecerAvaliadorView.as_view(),
        name="view_parecer_avaliador_psct",
    ),
    url(
        "^recurso/parecer_homologador/(?P<pk>[0-9]+)/$",
        views.ParecerHomologadorView.as_view(),
        name="view_parecer_homologador_psct",
    ),
    url(
        "^recurso/parecer/(?P<pk>[0-9]+)/$",
        views.ParecerView.as_view(),
        name="view_parecer_psct",
    ),
    url("^recurso/grupo/$", views.ListGrupoView.as_view(), name="list_grupo_psct"),
    url(
        "^recurso/redistribuir/(?P<pk>[0-9]+)/$",
        views.RedistribuirRecursoView.as_view(),
        name="redistribuir_recurso_psct",
    ),
    url(
        "^recurso/substituir_avaliador/(?P<recurso_pk>[0-9]+)/(?P<grupo_pk>[0-9]+)/(?P<avaliador_pk>[0-9]+)/$",
        views.SubstituirAvaliadorView.as_view(),
        name="substituir_avaliador_psct",
    ),
    url(
        "^recurso/substituir_homologador/(?P<recurso_pk>[0-9]+)/(?P<grupo_pk>[0-9]+)/(?P<homologador_pk>[0-9]+)/$",
        views.SubstituirHomologadorView.as_view(),
        name="substituir_homologador_psct",
    ),
    url(
        "^recurso/avaliador/$",
        views.ListAvaliadorView.as_view(),
        name="list_avaliador_psct",
    ),
    url(
        "^recurso/homologador/$",
        views.ListHomologadorView.as_view(),
        name="list_homologador_psct",
    ),
    url(
        "^recurso/permission_group/(?P<pk>[0-9]+)/change/$",
        views.UpdatePermissionGroupView.as_view(),
        name="change_permission_group_psct",
    ),
    url(
        "^recurso/remover_membro/(?P<grupo_pk>[0-9]+)/(?P<usuario_pk>[0-9]+)/$",
        views.RemoverMembroView.as_view(),
        name="remover_membro_psct",
    ),
    url(
        "^recurso/redistribuir/avaliador/(?P<fase_pk>[0-9]+)/$",
        views.RedistribuirRecursoAvaliacaoView.as_view(),
        name="redistribuir_avaliador_psct",
    ),
    url(
        "^recurso/redistribuir/homologador/(?P<fase_pk>[0-9]+)/$",
        views.RedistribuirRecursoHomologadorView.as_view(),
        name="redistribuir_homologador_psct",
    ),
    url(
        "^recurso/grupo/importar/avaliadores/$",
        views.ImportarAvaliadores.as_view(),
        name="importar_avaliadores_psct",
    ),
    url(
        "^recurso/grupo/importar/homologadores/$",
        views.ImportarHomologadores.as_view(),
        name="importar_homologadores_psct",
    ),
    url(
        "^recurso/resultado_recursos_pdf/(?P<pk>[0-9]+)/$",
        views.ResultadoRecursosPdf.as_view(),
        name="resultado_recursos_pdf",
    ),
]
