# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 10:39
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import noticias.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("corpo", ckeditor.fields.RichTextField()),
                ("publicado", models.BooleanField(default=False)),
                ("criacao", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("atualizacao", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "imagem",
                    models.ImageField(
                        upload_to=noticias.models.generate_imagem_noticia_path
                    ),
                ),
                ("alternative_text", models.CharField(max_length=100)),
                ("descricao", models.CharField(default="", max_length=200)),
            ],
            options={
                "ordering": ["-criacao"],
                "verbose_name": "Notícia",
                "verbose_name_plural": "Notícias",
            },
        ),
        migrations.CreateModel(
            name="PalavrasChave",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("palavra", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="noticia",
            name="palavras_chave",
            field=models.ManyToManyField(to="noticias.PalavrasChave"),
        ),
        migrations.AddField(
            model_name="noticia",
            name="responsavel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
