# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="noticia", name="alternative_text",),
        migrations.RemoveField(model_name="noticia", name="descricao",),
        migrations.AddField(
            model_name="noticia",
            name="resumo",
            field=models.CharField(
                default="",
                help_text="Descrição da notícia a ser publicada.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="noticia",
            name="texto_alternativo",
            field=models.CharField(
                default="",
                help_text="Texto alternativo à imagem, também usado para a acessibilidade.",
                max_length=100,
            ),
        ),
    ]
