# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0002_auto_20160315_1714"),
    ]

    operations = [
        migrations.AddField(
            model_name="palavraschave",
            name="slug",
            field=models.CharField(default="", max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
