# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields
import noticias.models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0003_palavraschave_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticia",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "imagem",
                "460x272",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="cropping",
            ),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="imagem",
            field=models.ImageField(
                help_text="Ao concluir o preenchimento do formulário, clique em 'Salvar e continuar editando' para personalizar o tamanho da imagem. ",
                upload_to=noticias.models.generate_imagem_noticia_path,
            ),
        ),
    ]
