# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0004_auto_20160318_0955"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assunto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="noticia",
            name="destaque",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="noticia",
            name="assunto",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="noticias.Assunto",
            ),
            preserve_default=False,
        ),
    ]
