# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0005_auto_20160323_0916"),
    ]

    operations = [
        migrations.AddField(
            model_name="assunto",
            name="pagina_inicial",
            field=models.BooleanField(
                default=False,
                help_text="Marque se desejar que as notícias mais recentes deste grupo sejam exibidas na página inicial.",
            ),
        ),
    ]
