# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0006_assunto_pagina_inicial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assunto",
            name="cor",
            field=models.CharField(
                choices=[
                    ("VERDE_ESCURO", "verde-escuro"),
                    ("AZUL_PETROLEO", "azul-petroleo"),
                    ("DOURADO", "dourado"),
                    ("ROXO", "roxo"),
                    ("MARROM_CLARO", "marrom-claro"),
                    ("LARANJA", "laranja"),
                    ("VERDE", "verde"),
                ],
                default="verde-escuro",
                help_text="Escolha a cor do título a ser exibido para este grupo de notícias.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="assunto",
            name="pagina_inicial",
            field=models.BooleanField(
                default=False,
                help_text="Marque se desejar que as notícias mais recentes deste grupo sejam exibidas na página inicial.",
                verbose_name="Página Inicial",
            ),
        ),
    ]
