# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 08:40
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import text


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Assunto = apps.get_model("noticias", "Assunto")
    db_alias = schema_editor.connection.alias
    for assunto in Assunto.objects.using(db_alias).all():
        assunto.slug = text.slugify(assunto.nome[:50])
        assunto.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0007_auto_20160323_1228"),
    ]

    operations = [
        migrations.AddField(
            model_name="assunto",
            name="slug",
            field=models.SlugField(null=True, blank=True, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name="assunto",
            name="slug",
            field=models.SlugField(null=False, unique=True),
        ),
    ]
