# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0008_assunto_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="resumo",
            field=models.CharField(
                help_text="Descrição da notícia a ser publicada.", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="texto_alternativo",
            field=models.CharField(
                help_text="Texto alternativo à imagem, também usado para a acessibilidade.",
                max_length=100,
            ),
        ),
    ]
