# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0009_auto_20160330_1828"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="texto_alternativo",
            field=models.CharField(
                help_text="Descreva a imagem. Será utilizado quando a imagem não puder ser carregada e quando o usuário estiver utilizando um leitor de tela.",
                max_length=100,
            ),
        ),
    ]
