# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0010_auto_20160617_1215"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="palavraschave", options={"ordering": ("palavra",)},
        ),
    ]
