# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 11:34
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0011_auto_20170127_0930"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "imagem",
                "460x272",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text="Clique e arraste para formar a área da imagem que será exibida no portal",
                hide_image_field=False,
                size_warning=False,
                verbose_name="Imagem que será exibida",
            ),
        ),
    ]
