# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-03 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("psct", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inscricao",
            options={
                "permissions": (
                    (
                        "recover_inscricao",
                        "Administrador pode recuperar dados de inscrição",
                    ),
                    ("view_inscricao", "Administrador pode ver os dados da inscrição"),
                    ("list_inscricao", "Administrador pode listar inscrições"),
                ),
                "verbose_name": "Inscrição",
                "verbose_name_plural": "Inscrições",
            },
        ),
    ]
