# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-31 16:51
from __future__ import unicode_literals

from django.db import migrations


def adicionar_candidatos(apps, schema_editor):
    group_class = apps.get_model("auth.group")
    user_class = apps.get_model("auth.user")
    us = user_class.objects.filter(pessoa__isnull=False)
    group, created = group_class.objects.get_or_create(name="Candidatos PSCT")
    group.user_set.add(*us)


def remover_candidatos(apps, schema_editor):
    group_class = apps.get_model("auth.group")
    user_class = apps.get_model("auth.user")
    us = user_class.objects.filter(pessoa__isnull=False)
    group = group_class.objects.get(name="Candidatos PSCT")
    group.user_set.remove(*us)


class Migration(migrations.Migration):

    dependencies = [
        ("psct", "0006_auto_20161014_0908"),
    ]

    operations = [migrations.RunPython(adicionar_candidatos, remover_candidatos)]
