# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-21 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("psct", "0009_auto_20161118_1319"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inscricaopreanalise",
            options={
                "ordering": (
                    "-pontuacao",
                    "-pontuacao_pt",
                    "-pontuacao_mt",
                    "nascimento",
                ),
                "verbose_name": "Inscrição Pré-Análise",
                "verbose_name_plural": "Inscrições Pré-Análise",
            },
        ),
    ]
