# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-15 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psct", "0012_resultado"),
    ]

    operations = [
        migrations.AddField(
            model_name="processoinscricao",
            name="multiplicador",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Quantidade de candidatos classificados por vaga",
                verbose_name="Multiplicador",
            ),
        ),
    ]
