# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("psct", "0013_processoinscricao_multiplicador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cancelamentoinscricao",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="comprovanteinscricao",
            name="inscricao",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comprovante",
                to="psct.Inscricao",
                verbose_name="Inscrição",
            ),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="destinatarios",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="psct.Consulta",
                verbose_name="Destinatários",
            ),
        ),
        migrations.AlterField(
            model_name="grupoedital",
            name="edital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="editais.Edital",
                verbose_name="Edital",
            ),
        ),
        migrations.AlterField(
            model_name="grupoedital",
            name="grupo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grupos_editais",
                to="auth.Group",
                verbose_name="Grupo",
            ),
        ),
        migrations.AlterField(
            model_name="modeloquestionario",
            name="edital",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="editais.Edital",
                verbose_name="edital",
            ),
        ),
        migrations.AlterField(
            model_name="pontuacaoinscricao",
            name="inscricao",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pontuacao",
                to="psct.Inscricao",
                verbose_name="Inscrição",
            ),
        ),
        migrations.AlterField(
            model_name="processoinscricao",
            name="edital",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processo_inscricao",
                to="editais.Edital",
                verbose_name="Edital",
            ),
        ),
        migrations.AlterField(
            model_name="regraexclusaogrupo",
            name="coluna",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="psct.Coluna",
                verbose_name="Coluna",
            ),
        ),
        migrations.AlterField(
            model_name="regraexclusaogrupo",
            name="grupo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="auth.Group",
                verbose_name="Grupo",
            ),
        ),
        migrations.AlterField(
            model_name="resultadopreliminarinscricao",
            name="justiticativa_indeferimento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="psct.JustificativaIndeferimento",
                verbose_name="Justificativa do Indeferimento",
            ),
        ),
        migrations.AlterField(
            model_name="resultadopreliminarinscricaoindeferida",
            name="justiticativa_indeferimento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="psct.JustificativaIndeferimento",
                verbose_name="Justificativa do Indeferimento",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoenvioemail",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="psct.Email",
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoenvioemail",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="vagasresultadopreliminar",
            name="modalidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="psct.Modalidade",
                verbose_name="Modalidade",
            ),
        ),
        migrations.AlterField(
            model_name="vagasresultadopreliminar",
            name="resultado_curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vagas",
                to="psct.ResultadoPreliminarCurso",
                verbose_name="Resultado Preliminar Curso",
            ),
        ),
    ]
