# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 10:16
from __future__ import unicode_literals

from django.db import migrations


def copia_dados(apps, schema_editor):
    Inscricao = apps.get_model("psct.Inscricao")
    for i in Inscricao.objects.all():
        i.nome = i.candidato.nome
        i.cpf = i.candidato.cpf
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ("psct", "0015_auto_20170530_1609"),
    ]

    operations = [migrations.RunPython(copia_dados)]
