# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-04 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("psct", "0016_copiadadoscandadito"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndeferimentoEspecial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Cadastro"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data da Atualização"
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscricao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indeferimento_especial",
                        to="psct.InscricaoPreAnalise",
                        verbose_name="Inscrição",
                    ),
                ),
                (
                    "motivo_indeferimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psct.JustificativaIndeferimento",
                        verbose_name="Motivo do Indeferimento",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
