# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-16 10:04
from __future__ import unicode_literals

from django.db import migrations

"""
    Mudança na inscrição dos candidatos a cursos do campus Sousa, participantes do edital número 
    73/2018 - PSCT - Cursos Tec. Subsequentes, conforme solicitação da COMPEC, através de e-mail 
    enviado no dia 13 de novembro de 2018, por Kelyson Nunes.
    
    Modificações:
    CANDIDATO                                   CURSO ANTERIOR              NOVO CURSO
    AGNA RAKIELLY (CPF: 097.813.644-67)         Informática (Vespertino)    Informática (Noturno)
    FRANCISCO MATEUS (CPF: 118.406.184-00)      Informática (Vespertino)    Informática (Noturno)
    ERICELMA DE MORAES (CPF: 055.586.244-50)    Agropecuária (Vespertino)   Agropecuária (Matutino)
    
    A solicitação está anexada na tarefa de número #240 no repositório do Portal do Estudante no 
    GitLab
"""


def change_inscricoes(apps, schema_editor):
    CursoNoCampus = apps.get_model("cursos.CursoNoCampus")
    agropecuaria_matutino = CursoNoCampus.objects.filter(pk=156).last()
    informatica_noturno = CursoNoCampus.objects.filter(pk=194).last()

    Inscricao = apps.get_model("psct.Inscricao")
    inscricoes_agropecuaria = Inscricao.objects.filter(pk=70373)
    inscricoes_agropecuaria.update(curso=agropecuaria_matutino)
    inscricoes_informatica = Inscricao.objects.filter(pk__in=[68465, 69279])
    inscricoes_informatica.update(curso=informatica_noturno)

    ComprovanteInscricao = apps.get_model("psct.ComprovanteInscricao")
    ComprovanteInscricao.objects.filter(inscricao__in=[68465, 69279, 70373]).delete()


def undo_change_inscricoes(apps, schema_editor):
    CursoNoCampus = apps.get_model("cursos.cursonocampus")
    agropecuaria_vespertino = CursoNoCampus.objects.filter(pk=193).last()
    informatica_vespertino = CursoNoCampus.objects.filter(pk=117).last()

    Inscricao = apps.get_model("psct.Inscricao")
    inscricoes_agropecuaria = Inscricao.objects.filter(pk=70373)
    inscricoes_agropecuaria.update(curso=agropecuaria_vespertino)
    inscricoes_informatica = Inscricao.objects.filter(pk__in=[68465, 69279])
    inscricoes_informatica.update(curso=informatica_vespertino)


class Migration(migrations.Migration):

    dependencies = [
        ("psct", "0017_indeferimentoespecial"),
    ]

    operations = [migrations.RunPython(change_inscricoes, undo_change_inscricoes)]
