# Generated by Django 2.2.14 on 2020-10-03 09:13

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0028_curso_selecao'),
        ('psct', '0021_auto_20191202_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='ano_enem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de realização do ENEM'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='com_segunda_opcao',
            field=models.BooleanField(default=False, verbose_name='Desejo me inscrever também para uma segunda opção de curso.'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='curso_segunda_opcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscricao_psct_2a_opcao', to='cursos.CursoSelecao', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='inscricaopreanalise',
            name='curso_segunda_opcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscricao_preanalise_2a_opcao', to='cursos.CursoSelecao', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='notaanual',
            name='ciencias_humanas',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Ciências humanas'),
        ),
        migrations.AddField(
            model_name='notaanual',
            name='ciencias_natureza',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Ciências da natureza'),
        ),
        migrations.AddField(
            model_name='notaanual',
            name='redacao',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Redação'),
        ),
        migrations.AddField(
            model_name='pontuacaoinscricao',
            name='nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Valor de desempate - Idade'),
        ),
        migrations.AddField(
            model_name='pontuacaoinscricao',
            name='valor_redacao',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Valor de desempate - Redação'),
        ),
        migrations.AddField(
            model_name='processoinscricao',
            name='possui_segunda_opcao',
            field=models.BooleanField(default=False, verbose_name='Disponibiliza a segunda opção de curso para os candidatos?'),
        ),
        migrations.AlterField(
            model_name='cursoedital',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cursos.CursoSelecao', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cursos.CursoSelecao', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='inscricaopreanalise',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes_preanalise', to='cursos.CursoSelecao', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='notaanual',
            name='ano',
            field=models.PositiveSmallIntegerField(verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='notaanual',
            name='geografia',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Geografia'),
        ),
        migrations.AlterField(
            model_name='notaanual',
            name='historia',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='História'),
        ),
        migrations.AlterField(
            model_name='notaanual',
            name='matematica',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Matemática'),
        ),
        migrations.AlterField(
            model_name='notaanual',
            name='portugues',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Português'),
        ),
        migrations.AlterField(
            model_name='pontuacaoinscricao',
            name='ensino_regular',
            field=models.BooleanField(default=False, verbose_name='Candidato cursou o ensino regular?'),
        ),
        migrations.AlterField(
            model_name='pontuacaoinscricao',
            name='valor',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='pontuacaoinscricao',
            name='valor_mt',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Valor de desempate MT'),
        ),
        migrations.AlterField(
            model_name='pontuacaoinscricao',
            name='valor_pt',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Valor de desempate PT'),
        ),
        migrations.AlterField(
            model_name='processoinscricao',
            name='cursos',
            field=models.ManyToManyField(limit_choices_to={'excluido': False}, to='cursos.CursoSelecao', verbose_name='Cursos'),
        ),
        migrations.AlterField(
            model_name='processoinscricao',
            name='formacao',
            field=models.CharField(choices=[('INTEGRADO', 'Técnico Integrado'), ('SUBSEQUENTE', 'Técnico Subsequente'), ('GRADUACAO', 'Graduação')], max_length=20, verbose_name='Formação'),
        ),
        migrations.AlterField(
            model_name='progressoanalise',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.CursoSelecao', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='resultadopreliminarcurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cursos.CursoSelecao', verbose_name='Curso'),
        ),
        migrations.AlterUniqueTogether(
            name='cursoedital',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cursoedital',
            constraint=models.UniqueConstraint(fields=('edital', 'curso'), name='cursoedital_unique'),
        ),
    ]
