# Generated by Django 2.2.14 on 2021-01-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psct', '0022_pscs'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='marcou_baixa_renda',
            field=models.BooleanField(default=False, verbose_name='Marcou Baixa Renda no questionário'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='marcou_escola_publica',
            field=models.BooleanField(default=False, verbose_name='Marcou Escola Pública no questionário'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='marcou_pcd',
            field=models.BooleanField(default=False, verbose_name='Marcou PCD no questionário'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='marcou_ppi',
            field=models.BooleanField(default=False, verbose_name='Marcou PPI no questionário'),
        ),
        migrations.AlterField(
            model_name='processoinscricao',
            name='formacao',
            field=models.CharField(choices=[('INTEGRADO', 'Técnico Integrado'), ('SUBSEQUENTE', 'Técnico Subsequente'), ('GRADUACAO', 'Graduação'), ('CONCOMITANTE', 'Concomitante')], max_length=20, verbose_name='Formação'),
        ),
    ]
