# Generated by Django 2.2.14 on 2021-01-18 22:47

import base.validators
from django.db import migrations, models
import psct.dbfields
import psct.models.inscricao


class Migration(migrations.Migration):

    dependencies = [
        ('psct', '0022_pscs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprovante',
            name='arquivo',
            field=psct.dbfields.DocumentFileField(help_text='Somente arquivo pdf, png, jpg, jpeg ou tiff com até 10 MB.', max_length=255, upload_to=psct.models.inscricao.get_comprovantes_directory, validators=[base.validators.FileValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'tiff'], max_size=10485760)], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='processoinscricao',
            name='formacao',
            field=models.CharField(choices=[('INTEGRADO', 'Técnico Integrado'), ('SUBSEQUENTE', 'Técnico Subsequente'), ('GRADUACAO', 'Graduação'), ('CONCOMITANTE', 'Concomitante')], max_length=20, verbose_name='Formação'),
        ),
    ]
