# Generated by Django 2.2.14 on 2021-01-20 16:25

import base.validators
from django.db import migrations
import psct.dbfields
import psct.models.inscricao


class Migration(migrations.Migration):

    dependencies = [
        ('psct', '0025_merge_20210119_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprovante',
            name='arquivo',
            field=psct.dbfields.DocumentFileField(help_text='Somente arquivo pdf, png, jpg, jpeg ou tiff com até 5 MB.', max_length=255, upload_to=psct.models.inscricao.get_comprovantes_directory, validators=[base.validators.FileValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'tiff'], max_size=5242880)], verbose_name='Arquivo'),
        ),
    ]
