# Generated by Django 2.2.14 on 2021-01-21 10:54

from django.db import migrations, models
import django.db.models.deletion
import processoseletivo.models


class Migration(migrations.Migration):

    dependencies = [
        ('psct', '0027_auto_20210120_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='modalidade_cota',
            field=models.ForeignKey(default=processoseletivo.models.ModalidadeEnum(3), on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes_psct', to='psct.Modalidade', verbose_name='Modalidade da Cota'),
        ),
    ]
