# Generated by Django 2.2.14 on 2021-01-21 11:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psct', '0028_auto_20210121_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaanual',
            name='ciencias_humanas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Ciências humanas'),
        ),
        migrations.AlterField(
            model_name='notaanual',
            name='geografia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Geografia'),
        ),
        migrations.AlterField(
            model_name='notaanual',
            name='historia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='História'),
        ),
        migrations.AlterField(
            model_name='notaanual',
            name='matematica',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Matemática'),
        ),
        migrations.AlterField(
            model_name='notaanual',
            name='portugues',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Português'),
        ),
        migrations.AlterField(
            model_name='notaanual',
            name='redacao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Redação'),
        ),
    ]
