# Generated by Django 2.2.14 on 2021-01-21 12:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psct', '0030_auto_20210121_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricaopreanalise',
            name='pontuacao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Pontuação'),
        ),
        migrations.AlterField(
            model_name='inscricaopreanalise',
            name='pontuacao_mt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Valor de desempate MT'),
        ),
        migrations.AlterField(
            model_name='inscricaopreanalise',
            name='pontuacao_pt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Valor de desempate PT'),
        ),
        migrations.AlterField(
            model_name='notaanualavaliador',
            name='geografia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Geografia'),
        ),
        migrations.AlterField(
            model_name='notaanualavaliador',
            name='historia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='História'),
        ),
        migrations.AlterField(
            model_name='notaanualavaliador',
            name='matematica',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Matemática'),
        ),
        migrations.AlterField(
            model_name='notaanualavaliador',
            name='portugues',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Português'),
        ),
        migrations.AlterField(
            model_name='notaanualhomologador',
            name='geografia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Geografia'),
        ),
        migrations.AlterField(
            model_name='notaanualhomologador',
            name='historia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='História'),
        ),
        migrations.AlterField(
            model_name='notaanualhomologador',
            name='matematica',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Matemática'),
        ),
        migrations.AlterField(
            model_name='notaanualhomologador',
            name='portugues',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Português'),
        ),
        migrations.AlterField(
            model_name='pontuacaoavaliador',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='pontuacaoavaliador',
            name='valor_mt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Valor de desempate MT'),
        ),
        migrations.AlterField(
            model_name='pontuacaoavaliador',
            name='valor_pt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Valor de desempate PT'),
        ),
        migrations.AlterField(
            model_name='pontuacaohomologador',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='pontuacaohomologador',
            name='valor_mt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Valor de desempate MT'),
        ),
        migrations.AlterField(
            model_name='pontuacaohomologador',
            name='valor_pt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, verbose_name='Valor de desempate PT'),
        ),
    ]
