# Generated by Django 2.2.14 on 2021-01-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psct', '0032_auto_20210121_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modalidade',
            options={'ordering': ('texto',), 'verbose_name': 'Modalidade de cota', 'verbose_name_plural': 'Modalidades de cota'},
        ),
        migrations.AlterModelOptions(
            name='modalidadevagacursoedital',
            options={'ordering': ('modalidade',), 'verbose_name': 'Vaga por modalidade do curso do edital', 'verbose_name_plural': 'Vagas por modalidade do curso do edital'},
        ),
    ]
