# Generated by Django 2.2.14 on 2021-02-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psct', '0033_auto_20210127_1353'),
        ('psct', '0033_auto_20210127_1821'),
    ]

    operations = [
    ]
