# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0002_auto_20160310_1037"),
    ]

    operations = [
        migrations.DeleteModel(name="PalavraChave",),
        migrations.AlterField(
            model_name="cursonocampus",
            name="palavras_chave",
            field=models.ManyToManyField(blank=True, to="noticias.PalavrasChave"),
        ),
    ]
