# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0003_auto_20160317_1657"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campus",
            name="diretor_ensino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cursos.Docente",
                verbose_name="Diretor de Ensino",
            ),
        ),
    ]
