# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-17 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0004_auto_20160330_1332"),
    ]

    operations = [
        migrations.AddField(
            model_name="campus",
            name="url",
            field=models.URLField(default="portal.ifba.edu.br", verbose_name="URL"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cursonocampus",
            name="disciplinas_atualizacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
