# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0005_auto_20160517_1011"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="lattes",
            field=models.URLField(
                blank=True,
                help_text="Endereço para o currículo Lattes.",
                max_length=100,
                null=True,
                verbose_name="Lattes",
            ),
        ),
    ]
