# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0006_auto_20160520_1042"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cursonocampus",
            name="ch_atividades_comp",
            field=models.IntegerField(
                blank=True,
                help_text="Carga horária mínima de atividades complementares necessárias à integralização do curso",
                null=True,
                verbose_name="Carga Horária de Atividades Complementares",
            ),
        ),
        migrations.AlterField(
            model_name="cursonocampus",
            name="ch_estagio",
            field=models.IntegerField(
                blank=True,
                help_text="Carga horária total de estágio necessária para a integralização do curso",
                null=True,
                verbose_name="Carga Horária de Estágio",
            ),
        ),
        migrations.AlterField(
            model_name="cursonocampus",
            name="ch_minima",
            field=models.IntegerField(
                blank=True,
                help_text="Carga horária mínima para a integralização do curso",
                null=True,
                verbose_name="Carga Horária Mínima",
            ),
        ),
        migrations.AlterField(
            model_name="cursonocampus",
            name="ch_rel_estagio",
            field=models.IntegerField(
                blank=True,
                help_text="Carga horária necessária para a execução do relatório de estágio",
                null=True,
                verbose_name="Carga Horária de Relatório de Estágio",
            ),
        ),
        migrations.AlterField(
            model_name="cursonocampus",
            name="ch_tcc",
            field=models.IntegerField(
                blank=True,
                help_text="Carga horária necessária para a execução do Trabalho de Conclusão de Curso",
                null=True,
                verbose_name="Carga Horária de TCC",
            ),
        ),
        migrations.AlterField(
            model_name="cursonocampus",
            name="ch_total",
            field=models.IntegerField(
                blank=True,
                help_text="Carga horária total do curso",
                null=True,
                verbose_name="Carga Horária Total",
            ),
        ),
        migrations.AlterField(
            model_name="cursonocampus",
            name="conceito",
            field=models.CharField(
                blank=True,
                help_text="Conceito do Curso",
                max_length=50,
                null=True,
                verbose_name="Conceito",
            ),
        ),
        migrations.AlterField(
            model_name="cursonocampus",
            name="cpc",
            field=models.CharField(
                blank=True,
                help_text="Conceito Preliminar de Curso",
                max_length=2,
                verbose_name="CPC",
            ),
        ),
        migrations.AlterField(
            model_name="cursonocampus",
            name="enade",
            field=models.CharField(
                blank=True,
                help_text="Nota do Curso no ENADE",
                max_length=1,
                verbose_name="ENADE",
            ),
        ),
        migrations.AlterField(
            model_name="cursonocampus",
            name="inicio",
            field=models.DateField(
                blank=True,
                help_text="Data de inicio do funcionamento do curso",
                null=True,
                verbose_name="Inicio",
            ),
        ),
        migrations.AlterField(
            model_name="cursonocampus",
            name="periodo_min_int",
            field=models.IntegerField(
                blank=True,
                help_text="Quantidade Mínima de bimestres/semestres/anos para a integralização do curso",
                null=True,
                verbose_name="Período Mínimo para Integralização",
            ),
        ),
        migrations.AlterField(
            model_name="cursopresencial",
            name="vagas_s1",
            field=models.IntegerField(verbose_name="Vagas no 1º Semestre"),
        ),
        migrations.AlterField(
            model_name="cursopresencial",
            name="vagas_s2",
            field=models.IntegerField(verbose_name="Vagas no 2º Semestre"),
        ),
        migrations.AlterField(
            model_name="docente",
            name="titulacao",
            field=models.CharField(
                choices=[
                    ("GRADUACAO", "Graduação"),
                    ("APERFEICOAMENTO", "Aperfeiçoamento"),
                    ("ESPECIALIZACAO", "Especialização"),
                    ("MESTRADO", "Mestrado"),
                    ("DOUTORADO", "Doutorado"),
                    ("NAOINFORMADO", "Não Informado"),
                ],
                max_length=15,
                verbose_name="Titulação",
            ),
        ),
    ]
