# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0007_auto_20160607_1717"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="nivel_formacao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TECNICO", "Técnico"),
                    ("GRADUACAO", "Graduação"),
                    ("POSGRADUACAO", "Pós-graduação"),
                ],
                max_length=16,
                null=True,
                verbose_name="Nível de Formação",
            ),
        ),
        migrations.AddField(
            model_name="cursonocampus",
            name="ch_pratica_docente",
            field=models.IntegerField(
                blank=True,
                help_text="Carga horária de prática docente para a integralização do curso. Somente para cursos de Licenciatura.",
                null=True,
                verbose_name="Carga Horária de Prática Docente",
            ),
        ),
        migrations.AddField(
            model_name="cursonocampus",
            name="codigo_suap",
            field=models.IntegerField(
                blank=True,
                help_text="Código utilizado no SUAP para identificar o curso",
                null=True,
                verbose_name="Código Suap",
            ),
        ),
        migrations.AlterField(
            model_name="cursonocampus",
            name="codigo",
            field=models.IntegerField(
                help_text="Código do curso cadastrado no e-MEC",
                unique=True,
                verbose_name="Código do Curso (e-Mec)",
            ),
        ),
        migrations.AlterField(
            model_name="cursonocampus",
            name="inicio",
            field=models.DateField(
                blank=True,
                help_text="Data de início do funcionamento do curso",
                null=True,
                verbose_name="Início",
            ),
        ),
        migrations.AlterField(
            model_name="cursonocampus",
            name="termino",
            field=models.DateField(
                blank=True,
                help_text="Data de encerramento do curso",
                null=True,
                verbose_name="Término",
            ),
        ),
        migrations.AlterField(
            model_name="cursopresencial",
            name="vagas_s1",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Vagas no 1º Semestre"
            ),
        ),
        migrations.AlterField(
            model_name="cursopresencial",
            name="vagas_s2",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Vagas no 2º Semestre"
            ),
        ),
    ]
