# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-20 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0008_auto_20160715_1340"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="nome",
            field=models.CharField(max_length=255, verbose_name="Nome"),
        ),
        migrations.AlterUniqueTogether(
            name="curso", unique_together=set([("nome", "nivel_formacao")]),
        ),
    ]
