# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0009_auto_20160720_1313"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cursonocampus",
            name="codigo",
            field=models.IntegerField(
                blank=True,
                help_text="Código do curso cadastrado no e-MEC",
                null=True,
                verbose_name="Código do Curso (e-Mec)",
            ),
        ),
        migrations.AlterField(
            model_name="cursonocampus",
            name="modalidade",
            field=models.CharField(
                blank=True,
                choices=[("PRESENCIAL", "Presencial"), ("EAD", "A distância")],
                max_length=16,
                null=True,
            ),
        ),
    ]
