# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 11:53
from __future__ import unicode_literals

import cursos.models
import cursos.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0010_auto_20160722_1002"),
    ]

    operations = [
        migrations.CreateModel(
            name="VagaCurso",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vagas_s1",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Vagas no 1º Semestre"
                    ),
                ),
                (
                    "vagas_s2",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Vagas no 2º Semestre"
                    ),
                ),
            ],
            options={"verbose_name": "Vaga", "verbose_name_plural": "Vagas",},
        ),
        migrations.AlterModelOptions(
            name="curso",
            options={
                "ordering": ("nome",),
                "verbose_name": "Curso Sistêmico",
                "verbose_name_plural": "Cursos Sistêmicos",
            },
        ),
        migrations.AlterModelOptions(
            name="cursonocampus",
            options={"verbose_name": "Curso", "verbose_name_plural": "Cursos"},
        ),
        migrations.AlterModelOptions(
            name="historico",
            options={"verbose_name": "Histórico", "verbose_name_plural": "Histórico"},
        ),
        migrations.AlterModelOptions(
            name="coordenador",
            options={
                "verbose_name": "Coordenação",
                "verbose_name_plural": "Coordenação",
            },
        ),
        migrations.RemoveField(model_name="tipodocumento", name="obrigatorio",),
        migrations.RemoveField(model_name="curso", name="campus",),
        migrations.AddField(
            model_name="vagacurso",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cursos.CursoNoCampus"
            ),
        ),
        migrations.AddField(
            model_name="vagacurso",
            name="polo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cursos.Polo",
            ),
        ),
        migrations.AddField(
            model_name="campus",
            name="aparece_no_menu",
            field=models.BooleanField(
                default=True,
                help_text="O campus aparecerá no menu de campi no Portal do Estudante.",
                verbose_name="Exibe URL.",
            ),
        ),
        migrations.AddField(
            model_name="coordenador",
            name="substituto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coordenador_substituto",
                to="cursos.Docente",
            ),
        ),
        migrations.AddField(
            model_name="disciplinacurso",
            name="plano",
            field=models.FileField(
                blank=True,
                help_text="Apenas arquivos .pdf no tamanho máximo de 2MB.",
                max_length=255,
                null=True,
                upload_to=cursos.models.generate_plano_disciplina_path,
                validators=[
                    cursos.validators.validate_file_size,
                    cursos.validators.validate_file_type,
                ],
            ),
        ),
        migrations.AddField(
            model_name="tipodocumento",
            name="obrigatorio_graduacao",
            field=models.BooleanField(
                default=False,
                help_text="Ao marcar este campo, você exige que o coordenador do curso cadastre\n                                                   pelo menos um documento deste tipo para cursos de graduação.",
                verbose_name="Obrigatório para curso de graduação",
            ),
        ),
        migrations.AddField(
            model_name="tipodocumento",
            name="obrigatorio_pos_graduacao",
            field=models.BooleanField(
                default=False,
                help_text="Ao marcar este campo, você exige que o coordenador do curso cadastre\n                                                   pelo menos um documento deste tipo para cursos de pós-graduação.",
                verbose_name="Obrigatório para curso de pós-graduação",
            ),
        ),
        migrations.AddField(
            model_name="tipodocumento",
            name="obrigatorio_tecnico",
            field=models.BooleanField(
                default=False,
                help_text="Ao marcar este campo, você exige que o coordenador do curso cadastre\n                                                   pelo menos um documento deste tipo para cursos técnicos.",
                verbose_name="Obrigatório para curso técnico",
            ),
        ),
        migrations.AlterField(
            model_name="cursonocampus",
            name="ch_minima",
            field=models.IntegerField(
                blank=True,
                help_text="Carga horária mínima para a integralização do curso",
                null=True,
                verbose_name="Carga Horária Mínima de integralização",
            ),
        ),
        migrations.AlterField(
            model_name="cursonocampus",
            name="modalidade",
            field=models.CharField(
                choices=[("PRESENCIAL", "Presencial"), ("EAD", "A distância")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="docente",
            name="titulacao",
            field=models.CharField(
                choices=[
                    ("GRADUACAO", "Graduação"),
                    ("APERFEICOAMENTO", "Aperfeiçoamento"),
                    ("ESPECIALIZACAO", "Especialização"),
                    ("MESTRADO", "Mestrado"),
                    ("DOUTORADO", "Doutorado"),
                    ("NAOINFORMADO", "Não Informado"),
                    ("NAODEFINIDO", "Não Definido"),
                ],
                max_length=15,
                verbose_name="Titulação",
            ),
        ),
        migrations.AlterField(
            model_name="disciplinacurso",
            name="periodo",
            field=models.IntegerField(default=1, verbose_name="Período ou Ano"),
        ),
        migrations.AlterField(
            model_name="coordenador",
            name="docente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cursos.Docente",
                verbose_name="Coordenador",
            ),
        ),
        migrations.AlterField(
            model_name="coordenador",
            name="email",
            field=models.EmailField(
                help_text="Informar o e-mail da coordenação.",
                max_length=128,
                verbose_name="E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="coordenador",
            name="substituto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coordenador_substituto",
                to="cursos.Docente",
                verbose_name="Coordenador Substituto",
            ),
        ),
        migrations.AlterField(
            model_name="coordenador",
            name="telefone",
            field=models.CharField(
                help_text="Informar o telefone da coordenação.",
                max_length=15,
                verbose_name="Telefone",
            ),
        ),
    ]
