# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 11:56
from __future__ import unicode_literals
from django.db import migrations
from django.db.models import Count
from base.utils import normalizar_nome_proprio


def remover_disciplinas_repetidas(apps, schema_editor):
    Disciplina = apps.get_model("cursos", "Disciplina")
    DisciplinaCurso = apps.get_model("cursos", "DisciplinaCurso")
    q = (
        Disciplina.objects.values("nome")
        .annotate(total=Count("nome"))
        .filter(total__gt=1)
    )
    for repetida in q:
        d_nome = repetida.get("nome")
        d = Disciplina.objects.filter(nome=d_nome).first()
        dcs = DisciplinaCurso.objects.filter(disciplina__nome=d_nome)
        dcs.update(disciplina=d)
        print("excluindo disciplina " + d_nome + "...")
        Disciplina.objects.filter(nome=d_nome).exclude(pk=d.pk).delete()


def disciplinas_capitalize(apps, schema_editor):
    from cursos.models import SIGLAS_DISCIPLINA

    Disciplina = apps.get_model("cursos", "Disciplina")
    for disciplina in Disciplina.objects.all():
        disciplina.nome = normalizar_nome_proprio(disciplina.nome, SIGLAS_DISCIPLINA)
        disciplina.save()


def migrate_vagas(apps, schema_editor):
    VagasEAD = apps.get_model("cursos", "VagasEAD")
    VagaCurso = apps.get_model("cursos", "VagaCurso")
    CursoPresencial = apps.get_model("cursos", "CursoPresencial")

    for vaga_ead in VagasEAD.objects.all():
        vaga_curso = VagaCurso()
        vaga_curso.curso = vaga_ead.curso.cursonocampus_ptr
        vaga_curso.polo = vaga_ead.polo
        vaga_curso.vagas_s1 = vaga_ead.vagas_s1
        vaga_curso.vagas_s2 = vaga_ead.vagas_s2
        vaga_curso.save()

    for curso_presencial in CursoPresencial.objects.all():
        vaga_curso = VagaCurso()
        vaga_curso.curso = curso_presencial.cursonocampus_ptr
        vaga_curso.vagas_s1 = curso_presencial.vagas_s1
        vaga_curso.vagas_s2 = curso_presencial.vagas_s2
        vaga_curso.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0011_auto_20160821_1153"),
    ]

    operations = [
        migrations.RunPython(disciplinas_capitalize),
        migrations.RunPython(remover_disciplinas_repetidas),
        migrations.RunPython(migrate_vagas),
    ]
