# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0014_auto_20160930_1629"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cursonocampus",
            options={
                "ordering": ("curso__nome",),
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
            },
        ),
    ]
