# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0017_campus_servidores"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocenteExterno",
            fields=[],
            options={
                "verbose_name": "Docente Externo",
                "verbose_name_plural": "Docentes Externos",
                "proxy": True,
            },
            bases=("cursos.docente",),
        ),
        migrations.AddField(
            model_name="docente",
            name="externo",
            field=models.BooleanField(default=False, verbose_name="Externo"),
        ),
        migrations.AlterField(
            model_name="docente",
            name="admissao",
            field=models.DateField(
                blank=True,
                help_text="Data que entrou em exercício como docente da instituição.",
                null=True,
                verbose_name="Admissão",
            ),
        ),
        migrations.AlterField(
            model_name="docente",
            name="matricula",
            field=models.CharField(
                help_text="Sem dígito verificador.",
                max_length=11,
                unique=True,
                verbose_name="Matrícula",
            ),
        ),
        migrations.AlterField(
            model_name="docente",
            name="rt",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DE", "Dedicação Exclusiva"),
                    ("TI", "Tempo Integral (40h)"),
                    ("TP", "Tempo Parcial (20h)"),
                ],
                max_length=10,
                null=True,
                verbose_name="Regime de Trabalho",
            ),
        ),
        migrations.AlterField(
            model_name="docente",
            name="titulacao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GRADUACAO", "Graduação"),
                    ("APERFEICOAMENTO", "Aperfeiçoamento"),
                    ("ESPECIALIZACAO", "Especialização"),
                    ("MESTRADO", "Mestrado"),
                    ("DOUTORADO", "Doutorado"),
                    ("NAOINFORMADO", "Não Informado"),
                    ("NAODEFINIDO", "Não Definido"),
                ],
                max_length=15,
                null=True,
                verbose_name="Titulação",
            ),
        ),
    ]
