# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0018_auto_20170216_1845"),
    ]

    operations = [
        migrations.AddField(
            model_name="ies",
            name="igc",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Índice Geral de Cursos",
            ),
        ),
        migrations.AlterField(
            model_name="ies",
            name="ci",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Conceito Institucional",
            ),
        ),
    ]
