# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 11:59
from __future__ import unicode_literals
from django.db import migrations


def substitui_curso(substituido, substituto):
    nomes_relacoes_fk = [
        "vaga_set",
        "inscricoes_mec",
        "chamada_set",
        "inscricao_set",
        "cursoedital_set",
        "inscricoes_preanalise",
        "progressoanalise_set",
        "resultadopreliminarcurso_set",
    ]
    nomes_relacoes_m2m = ["processoinscricao_set"]

    for nome in nomes_relacoes_fk + nomes_relacoes_m2m:
        relacoes = getattr(substituido, nome).all()
        getattr(substituto, nome).add(*relacoes)
        if nome in nomes_relacoes_m2m:
            getattr(substituido, nome).remove(*relacoes)


def substituicao_curso_psct(apps, schema_editor):
    CursoNoCampus = apps.get_model("cursos", "CursoNoCampus")
    try:
        curso_substituido = CursoNoCampus.objects.get(pk=78)  # old 78
        curso_substituto = CursoNoCampus.objects.get(pk=158)  # new 158
        substitui_curso(curso_substituido, curso_substituto)
    except CursoNoCampus.DoesNotExist:
        pass


def reverte_substituicao_curso_psct(apps, schema_editor):
    CursoNoCampus = apps.get_model("cursos", "CursoNoCampus")
    try:
        curso_substituido = CursoNoCampus.objects.get(pk=78)
        curso_substituto = CursoNoCampus.objects.get(pk=158)
        substitui_curso(
            curso_substituto, curso_substituido
        )  # argumentos em ordem invertida
    except CursoNoCampus.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0019_auto_20170220_1552"),
    ]

    operations = [
        migrations.RunPython(substituicao_curso_psct, reverte_substituicao_curso_psct),
    ]
