# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0020_auto_20170324_1159"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordenador",
            name="substituto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coordenador_substituto",
                to="cursos.Docente",
                verbose_name="Coordenador Substituto",
            ),
        ),
        migrations.AlterField(
            model_name="vagacurso",
            name="polo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cursos.Polo",
            ),
        ),
    ]
