# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0021_auto_20170419_1339"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tipodocumento",
            options={
                "ordering": ["nome"],
                "verbose_name": "Tipo de Documento",
                "verbose_name_plural": "Tipos de Documentos",
            },
        ),
    ]
