# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-28 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0023_auto_20171004_1650"),
    ]

    operations = [
        migrations.AddField(
            model_name="cursonocampus",
            name="video_catalogo",
            field=models.URLField(
                blank=True,
                help_text='Copiar e colar o endereço "src" que aparece na opção de compartilhamento "Incorporar" do YouTube.',
                null=True,
                verbose_name="URL de vídeo descritivo do curso",
            ),
        ),
    ]
