# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-21 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0024_cursonocampus_video_catalogo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cursonocampus",
            name="excluido",
            field=models.BooleanField(
                default=False,
                help_text="Esta opção removerá a exibição do curso nas listagens",
                verbose_name="Excluído",
            ),
        ),
    ]
