# Generated by Django 2.2.3 on 2020-03-25 18:00

from django.db import migrations, models
import django.db.models.deletion

from base.choices import TipoServidor


def definir_docentes(apps, schema_editor):
    Servidor = apps.get_model("cursos", "servidor")
    Servidor.objects.exclude(externo=True).update(tipo=TipoServidor.DOCENTE.name)
    Servidor.objects.filter(externo=True).update(tipo=TipoServidor.DOCENTE_EXTERNO.name)


def restaurar_docentes_externos(apps, schema_editor):
    Servidor = apps.get_model("cursos", "servidor")
    Servidor.objects.filter(tipo=TipoServidor.DOCENTE_EXTERNO.name).update(externo=True)


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0025_cursonocampus_excluido"),
    ]

    operations = [
        migrations.DeleteModel(name="DocenteExterno",),
        migrations.RenameModel("Docente", "Servidor"),
        migrations.RenameModel("Coordenador", "Coordenacao"),
        migrations.RenameField("Coordenacao", "docente", "coordenador"),
        migrations.AlterModelOptions(
            name="coordenacao",
            options={
                "verbose_name": "Coordenação de curso",
                "verbose_name_plural": "Coordenações de cursos",
            },
        ),
        migrations.AlterModelOptions(
            name="servidor",
            options={"verbose_name": "Servidor", "verbose_name_plural": "Servidores"},
        ),
        migrations.AlterField(
            model_name="coordenacao",
            name="coordenador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coordenador",
                to="cursos.Servidor",
                verbose_name="Coordenador",
            ),
        ),
        migrations.AlterField(
            model_name="coordenacao",
            name="substituto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coordenador_substituto",
                to="cursos.Servidor",
                verbose_name="Coordenador substituto",
            ),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="admissao",
            field=models.DateField(
                blank=True,
                help_text="Data que o servidor entrou em exercício na instituição.",
                null=True,
                verbose_name="Data de admissão",
            ),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="lattes",
            field=models.URLField(
                blank=True,
                help_text="Endereço para o currículo Lattes.",
                max_length=100,
                null=True,
                verbose_name="Currículo Lattes",
            ),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="matricula",
            field=models.CharField(
                help_text="Matrícula SIAPE sem dígito verificador.",
                max_length=11,
                unique=True,
                verbose_name="Matrícula",
            ),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="rt",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DE", "Dedicação Exclusiva"),
                    ("TI", "Tempo Integral (40h)"),
                    ("TP", "Tempo Parcial (20h)"),
                ],
                max_length=10,
                null=True,
                verbose_name="Regime de trabalho",
            ),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="titulacao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GRADUACAO", "Graduação"),
                    ("APERFEICOAMENTO", "Aperfeiçoamento"),
                    ("ESPECIALIZACAO", "Especialização"),
                    ("MESTRADO", "Mestrado"),
                    ("DOUTORADO", "Doutorado"),
                    ("NAOINFORMADO", "Não Informado"),
                    ("NAODEFINIDO", "Não Definido"),
                ],
                max_length=15,
                null=True,
                verbose_name="Titulação acadêmica",
            ),
        ),
        migrations.CreateModel(
            name="DocenteExterno",
            fields=[],
            options={
                "verbose_name": "Docente Externo",
                "verbose_name_plural": "Docentes Externos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cursos.servidor",),
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[],
            options={
                "verbose_name": "Docente",
                "verbose_name_plural": "Docentes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cursos.servidor",),
        ),
        migrations.AddField(
            model_name="servidor",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("TAE", "Técnico administrativo"),
                    ("DOCENTE", "Docente"),
                    ("DOCENTE_EXTERNO", "Docente externo"),
                    ("TERCEIRIZADO", "Prestador de serviços"),
                ],
                default="TAE",
                max_length=16,
                verbose_name="Tipo de servidor",
            ),
        ),
        migrations.RunPython(definir_docentes, restaurar_docentes_externos),
        migrations.RemoveField(model_name="servidor", name="externo",),
    ]
