# Generated by Django 2.2.12 on 2020-07-15 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0026_auto_20200324_1632"),
    ]

    operations = [
        migrations.CreateModel(
            name="CursoSelecao",
            fields=[
                (
                    "cursonocampus_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cursos.CursoNoCampus",
                    ),
                ),
                (
                    "polo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cursos_selecao",
                        to="cursos.Polo",
                        verbose_name="Polo EAD",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso para seleção",
                "verbose_name_plural": "Cursos para seleções",
            },
            bases=("cursos.cursonocampus",),
        ),
    ]
