# Generated by Django 2.2.12 on 2020-07-15 10:22

from django.db import migrations
from django.db import connection


def fill_curso_selecao(apps, schema_editor):
    CursoCampus = apps.get_model("cursos.CursoNoCampus")
    CursoSelecao = apps.get_model("cursos.CursoSelecao")
    VagaCurso = apps.get_model("cursos.VagaCurso")
    for curso in CursoCampus.objects.all():
        cursor = connection.cursor()
        cursor.execute(
            "INSERT INTO cursos_cursoselecao (cursonocampus_ptr_id) VALUES (%s);",
            [curso.id],
        )
    for vaga in VagaCurso.objects.filter(polo__isnull=False):
        if vaga.curso.modalidade == "EAD":
            data = dict(vaga.curso.__dict__)
            data["polo_id"] = vaga.polo_id
            del data["id"]
            del data["_state"]
            CursoSelecao.objects.create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0027_cursoselecao"),
    ]

    operations = [migrations.RunPython(fill_curso_selecao, migrations.RunPython.noop)]
