# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidatos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caracterizacao",
            name="qtd_filhos",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Quantidade de filhos"
            ),
        ),
    ]
