# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("candidatos", "0003_auto_20170110_0932"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caracterizacao",
            name="escola_ensino_medio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escola_ensino_medio",
                to="candidatos.TipoEscola",
                verbose_name="Tipo de escola que cursou o ensino médio",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="frequencia_acesso_internet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="candidatos.TipoAcessoInternet",
                verbose_name="Frequência de Acesso à Internet",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="razao_ausencia_educacional",
            field=models.ForeignKey(
                blank=True,
                help_text="Informe o motivo pelo qual você ficou sem estudar caso tenha marcado a opção anterior.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="candidatos.RazaoAfastamentoEducacional",
                verbose_name="Motivo da Ausência Escolar",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="tipo_area_escola_ensino_medio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tipo_area_escola_ensino_medio",
                to="candidatos.TipoAreaResidencial",
                verbose_name="Tipo de localização da escola que fez o ensino médio",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="tipo_servico_saude",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="candidatos.TipoServicoSaude",
                verbose_name="Serviço de saúde que você mais utiliza",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="trabalho_situacao",
            field=models.ForeignKey(
                help_text="Situação em que você se encontra no mercado de trabalho.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="candidatos.SituacaoTrabalho",
                verbose_name="Situação de trabalho",
            ),
        ),
    ]
