# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("candidatos", "0005_auto_20170519_1558"),
    ]

    operations = [
        migrations.RemoveField(model_name="inscricaocaracterizacao", name="candidato",),
        migrations.RemoveField(
            model_name="inscricaocaracterizacao", name="moradia_responsavel_financeiro",
        ),
        migrations.RemoveField(
            model_name="integrantefamiliarcaracterizacao", name="estado_civil",
        ),
        migrations.RemoveField(
            model_name="integrantefamiliarcaracterizacao",
            name="inscricao_caracterizacao",
        ),
        migrations.RemoveField(
            model_name="integrantefamiliarcaracterizacao", name="situacao_trabalho",
        ),
        migrations.AlterModelOptions(
            name="caracterizacao",
            options={
                "ordering": ["candidato__nome"],
                "verbose_name": "Caracterização Social",
                "verbose_name_plural": "Caracterizações Sociais",
            },
        ),
        migrations.AlterModelOptions(
            name="comunicadocandidato",
            options={
                "verbose_name": "Comunicado ao Candidato",
                "verbose_name_plural": "Comunicados aos Candidatos",
            },
        ),
        migrations.AlterModelOptions(
            name="raca",
            options={"verbose_name": "Etnia", "verbose_name_plural": "Etnias"},
        ),
        migrations.AlterModelOptions(
            name="tipoescola",
            options={
                "verbose_name": "Tipo de Escola",
                "verbose_name_plural": "Tipos de Escolas",
            },
        ),
        migrations.RenameField(
            model_name="caracterizacao",
            old_name="estado_civil_pais",
            new_name="estado_civil_mae",
        ),
        migrations.AddField(
            model_name="caracterizacao",
            name="estado_civil_pai",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pais_candidatos",
                to="candidatos.EstadoCivil",
                verbose_name="Estado Civil do Pai",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="companhia_domiciliar",
            field=models.ForeignKey(
                help_text="Com quem você mora?",
                on_delete=django.db.models.deletion.CASCADE,
                to="candidatos.CompanhiaDomiciliar",
                verbose_name="Companhia domiciliar",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="contribuintes_renda_familiar",
            field=models.ManyToManyField(
                blank=True,
                help_text="Pessoas que contribuem para rendar familiar.",
                to="candidatos.ContribuinteRendaFamiliar",
                verbose_name="Contribuintes da renda familiar",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="declara_veracidade",
            field=models.BooleanField(
                verbose_name="DECLARO, para os fins de direito, sob as penas da lei, que as informações e os documentos que apresento para pré-matrícula no IFPB, são fiéis à verdade e condizentes com a realidade dos fatos. Fico ciente, portanto, que a falsidade desta declaração configura-se em crime previsto no Código Penal Brasileiro e passível de apuração na forma da Lei."
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="escola_ensino_fundamental",
            field=models.ForeignKey(
                help_text="Informe o tipo de escola que você cursou durante o Ensino Fundamental.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escola_ensino_fundamental",
                to="candidatos.TipoEscola",
                verbose_name="Tipo de escola do Ensino Fundamental",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="escola_ensino_medio",
            field=models.ForeignKey(
                blank=True,
                help_text="Informe o tipo de escola que você cursou durante o Ensino Médio.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escola_ensino_medio",
                to="candidatos.TipoEscola",
                verbose_name="Tipo de escola do Ensino Médio",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="escolaridade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidato",
                to="candidatos.NivelEscolaridade",
                verbose_name="Nivel de escolaridade",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="estado_civil",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alunos",
                to="candidatos.EstadoCivil",
                verbose_name="Estado Civil",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="ficou_tempo_sem_estudar",
            field=models.BooleanField(
                default=False,
                help_text="Marque caso tenha permanecido algum tempo sem estudar.",
                verbose_name="Ausência escolar",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="frequencia_acesso_internet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="candidatos.TipoAcessoInternet",
                verbose_name="Frequência de Acesso à Internet",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="local_acesso_internet",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Local de acesso à internet",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="mae_falecida",
            field=models.BooleanField(verbose_name="Mãe falecida"),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="mae_nivel_escolaridade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mae",
                to="candidatos.NivelEscolaridade",
                verbose_name="Nível de escolaridade da mãe",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="meio_transporte_utilizado",
            field=models.ManyToManyField(
                blank=True,
                help_text="Meio de transporte que você utiliza/utilizará para se deslocar.",
                to="candidatos.MeioTransporte",
                verbose_name="Meio de transporte",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="necessidade_especial",
            field=models.ManyToManyField(
                blank=True,
                to="candidatos.NecessidadeEspecial",
                verbose_name="Necessidades educacionais especiais",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="nome_escola_ensino_fundamental",
            field=models.CharField(
                help_text="Informe o nome da escola que você cursou durante o Ensino Fundamental.",
                max_length=50,
                verbose_name="Nome da escola do Ensino Fundamental",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="nome_escola_ensino_medio",
            field=models.CharField(
                blank="True",
                help_text="Informe o nome da escola que você cursou durante o Ensino Médio.",
                max_length=50,
                null=True,
                verbose_name="Nome da escola do Ensino Médio",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="pai_falecido",
            field=models.BooleanField(verbose_name="Pai falecido"),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="pai_nivel_escolaridade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pai",
                to="candidatos.NivelEscolaridade",
                verbose_name="Nível de escolaridade do pai",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="possui_conhecimento_idiomas",
            field=models.BooleanField(
                default=False, verbose_name="Conhecimento em idiomas"
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="possui_conhecimento_informatica",
            field=models.BooleanField(
                default=False, verbose_name="Conhecimento em informática"
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="qtd_filhos",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Quantidade de filhos"
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="quantidade_computadores",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Quantidade de computadores desktop que possui",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="quantidade_netbooks",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Quantidade de netbooks que possui"
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="quantidade_notebooks",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Quantidade de notebooks que possui"
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="quantidade_smartphones",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Quantidade de smartphones que possui",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="responsavel_financeir_trabalho_situacao",
            field=models.ForeignKey(
                blank=True,
                help_text="Situação em que seu pai se encontra no mercado de trabalho.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsavel_financeiro",
                to="candidatos.SituacaoTrabalho",
                verbose_name="Situação de trabalho do principal responsável financeiro",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="responsavel_financeiro",
            field=models.ForeignKey(
                blank=True,
                help_text="Pessoa responsável pela renda familiar",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsavel_financeiro",
                to="candidatos.ContribuinteRendaFamiliar",
                verbose_name="Principal responsável pela renda familiar",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="responsavel_financeiro_nivel_escolaridade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsavel_financeiro",
                to="candidatos.NivelEscolaridade",
                verbose_name="Nível de escolaridade do principal responsável financeiro",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="tipo_area_escola_ensino_fundamental",
            field=models.ForeignKey(
                help_text="Informe a localização da escola que você cursou durante o Ensino Fundamental.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tipo_area_escola_ensino_fundamental",
                to="candidatos.TipoAreaResidencial",
                verbose_name="Localização da escola do Ensino Fundamental",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="tipo_area_escola_ensino_medio",
            field=models.ForeignKey(
                blank=True,
                help_text="Informe a localização da escola que você curso durante o Ensino Médio",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tipo_area_escola_ensino_medio",
                to="candidatos.TipoAreaResidencial",
                verbose_name="Localização da escola do Ensino Médio",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="tipo_area_residencial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="candidatos.TipoAreaResidencial",
                verbose_name="Tipo de área residencial em que reside",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="tipo_imovel_residencial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="candidatos.TipoImovelResidencial",
                verbose_name="Tipo de imóvel em que reside",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="tipo_servico_saude",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="candidatos.TipoServicoSaude",
                verbose_name="Serviço de saúde que você mais utiliza",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="trabalho_situacao",
            field=models.ForeignKey(
                blank=True,
                help_text="Situação em que você se encontra no mercado de trabalho.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="candidatos.SituacaoTrabalho",
                verbose_name="Situação de trabalho",
            ),
        ),
        migrations.DeleteModel(name="InscricaoCaracterizacao",),
        migrations.DeleteModel(name="IntegranteFamiliarCaracterizacao",),
    ]
