# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("candidatos", "0006_auto_20170727_1205"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caracterizacao",
            name="estado_civil_mae",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maes_candidatos",
                to="candidatos.EstadoCivil",
                verbose_name="Estado Civil da Mãe",
            ),
        ),
        migrations.AddField(
            model_name="estadocivil",
            name="valor_suap",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Valor utilizado no Suap"
            ),
        ),
        migrations.AddField(
            model_name="tipoescola",
            name="valor_suap",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Valor utilizado no Suap"
            ),
        ),
        migrations.AddField(
            model_name="raca",
            name="valor_suap",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Valor utilizado no Suap"
            ),
        ),
    ]
