# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidatos", "0007_auto_20170727_1212"),
    ]

    operations = [
        migrations.AddField(
            model_name="caracterizacao",
            name="estado_escola_ensino_fundamental",
            field=models.CharField(
                blank="True",
                choices=[
                    ("AC", "Acre"),
                    ("AL", "Alagoas"),
                    ("AP", "Amapa"),
                    ("AM", "Amazonas"),
                    ("BA", "Bahia"),
                    ("CE", "Ceará"),
                    ("DF", "Distrito Federal"),
                    ("ES", "Espírito Santo"),
                    ("GO", "Goiás"),
                    ("MA", "Maranhão"),
                    ("MT", "Mato Grosso"),
                    ("MS", "Mato Grosso do Sul"),
                    ("MG", "Minas Gerais"),
                    ("PA", "Pará"),
                    ("PB", "Paraíba"),
                    ("PR", "Paraná"),
                    ("PE", "Pernambuco"),
                    ("PI", "Piauí"),
                    ("RJ", "Rio de Janeiro"),
                    ("RN", "Rio Grande do Norte"),
                    ("RS", "Rio Grande do Sul"),
                    ("RO", "Rondônia"),
                    ("RR", "Roraima"),
                    ("SC", "Santa Catarina"),
                    ("SP", "São Paulo"),
                    ("SE", "Sergipe"),
                    ("TO", "Tocantis"),
                ],
                max_length=50,
                null=True,
                verbose_name="Estado onde está localizada a Escola de Ensino Fundamental",
            ),
        ),
        migrations.AddField(
            model_name="caracterizacao",
            name="estado_escola_ensino_medio",
            field=models.CharField(
                blank="True",
                choices=[
                    ("AC", "Acre"),
                    ("AL", "Alagoas"),
                    ("AP", "Amapa"),
                    ("AM", "Amazonas"),
                    ("BA", "Bahia"),
                    ("CE", "Ceará"),
                    ("DF", "Distrito Federal"),
                    ("ES", "Espírito Santo"),
                    ("GO", "Goiás"),
                    ("MA", "Maranhão"),
                    ("MT", "Mato Grosso"),
                    ("MS", "Mato Grosso do Sul"),
                    ("MG", "Minas Gerais"),
                    ("PA", "Pará"),
                    ("PB", "Paraíba"),
                    ("PR", "Paraná"),
                    ("PE", "Pernambuco"),
                    ("PI", "Piauí"),
                    ("RJ", "Rio de Janeiro"),
                    ("RN", "Rio Grande do Norte"),
                    ("RS", "Rio Grande do Sul"),
                    ("RO", "Rondônia"),
                    ("RR", "Roraima"),
                    ("SC", "Santa Catarina"),
                    ("SP", "São Paulo"),
                    ("SE", "Sergipe"),
                    ("TO", "Tocantis"),
                ],
                max_length=50,
                null=True,
                verbose_name="Estado onde está localizada a Escola de Ensino Médio",
            ),
        ),
        migrations.AddField(
            model_name="caracterizacao",
            name="municipio_escola_ensino_fundamental",
            field=models.CharField(
                blank="True",
                max_length=50,
                null=True,
                verbose_name="Município da escola de Ensino Fundamental",
            ),
        ),
        migrations.AddField(
            model_name="caracterizacao",
            name="municipio_escola_ensino_medio",
            field=models.CharField(
                blank="True",
                max_length=50,
                null=True,
                verbose_name="Município da escola de Ensino Médio",
            ),
        ),
    ]
