# Generated by Django 2.2.1 on 2019-05-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidatos", "0008_auto_20170828_1809"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caracterizacao",
            name="ficou_tempo_sem_estudar",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Marque caso tenha permanecido algum tempo sem estudar.",
                verbose_name="Ausência escolar",
            ),
        ),
        migrations.AlterField(
            model_name="caracterizacao",
            name="possui_conhecimento_informatica",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Conhecimento em informática"
            ),
        ),
    ]
