# Generated by Django 2.2.14 on 2021-01-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0011_auto_20210118_2247'),
        ('candidatos', '0011_auto_20210118_1813'),
    ]

    operations = [
    ]
