# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 10:39
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import editais.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("processoseletivo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cronograma",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome do Período"),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[("SELECAO", "Seleção"), ("CONVOCACAO", "Convocação")],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("inicio", models.DateField(verbose_name="Início")),
                ("fim", models.DateField(verbose_name="Fim")),
            ],
            options={
                "verbose_name": "Cronograma",
                "verbose_name_plural": "Cronogramas",
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("RESULTADO", "Resultado"),
                            ("PROVA", "Prova"),
                            ("GABARITO", "Gabarito"),
                            ("EDITAL", "Edital"),
                            ("RECURSO", "Recurso"),
                            ("LOCALPROVA", "Local de Prova"),
                            ("ANEXO", "Anexo"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        help_text="Será aceito arquivo com tamanho máximo 2MB e que seja do tipo: pdf.",
                        upload_to="",
                        validators=[
                            editais.validators.FileValidator(
                                allowed_extensions=["pdf"], max_size=2097152
                            )
                        ],
                    ),
                ),
                (
                    "data_upload",
                    models.DateField(auto_now_add=True, verbose_name="Data de upload"),
                ),
            ],
            options={"verbose_name": "Anexo", "verbose_name_plural": "Anexos",},
        ),
        migrations.CreateModel(
            name="Edital",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("numero", models.PositiveSmallIntegerField(verbose_name="Número")),
                ("ano", models.PositiveIntegerField(verbose_name="Ano")),
                (
                    "data_publicacao",
                    models.DateField(verbose_name="Data de Publicação"),
                ),
                (
                    "encerrado",
                    models.BooleanField(default=False, verbose_name="Edital Encerrado"),
                ),
                (
                    "publicado",
                    models.BooleanField(default=False, verbose_name="Edital Publicado"),
                ),
                ("descricao", ckeditor.fields.RichTextField(verbose_name="Descrição")),
                ("prazo_pagamento", models.DateField(verbose_name="Data de Pagamento")),
                (
                    "link_inscricoes",
                    models.URLField(
                        blank=True, null=True, verbose_name="Link para Inscrições"
                    ),
                ),
                (
                    "setor_responsavel",
                    models.CharField(max_length=255, verbose_name="Setor Responsável"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ABERTURA", "Abertura"),
                            ("RETIFICACAO", "Retificação"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "palavra_chave",
                    models.CharField(
                        help_text="Palavra-chave para relacionar com as notícias referentes a esse edital.",
                        max_length=30,
                        verbose_name="Palavra-chave",
                    ),
                ),
                (
                    "edicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processoseletivo.Edicao",
                        verbose_name="Edição de Processo Seletivo",
                    ),
                ),
                (
                    "retificado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retificacoes",
                        to="editais.Edital",
                        verbose_name="Edital Retificado",
                    ),
                ),
            ],
            options={"verbose_name": "Edital", "verbose_name_plural": "Editais",},
        ),
        migrations.CreateModel(
            name="NivelSelecao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "vagas",
                    models.PositiveIntegerField(verbose_name="Quantidade de Vagas"),
                ),
                (
                    "valor_inscricao",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Taxa de Inscrição",
                    ),
                ),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="niveis_selecao",
                        to="editais.Edital",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nível de Seleção",
                "verbose_name_plural": "Níveis de Seleção",
            },
        ),
        migrations.CreateModel(
            name="PeriodoConvocacao",
            fields=[
                (
                    "cronograma_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="editais.Cronograma",
                    ),
                ),
                (
                    "evento",
                    models.CharField(
                        choices=[
                            ("INTERESSE", "Manifestação de Interesse"),
                            ("ANALISE", "Análise de documentação"),
                            ("CONFIRMACAO", "Confirmação de matrícula"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cronogramas_convocacao",
                        to="processoseletivo.Etapa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Período Convocação",
                "verbose_name_plural": "Períodos Convocações",
            },
            bases=("editais.cronograma",),
        ),
        migrations.CreateModel(
            name="PeriodoSelecao",
            fields=[
                (
                    "cronograma_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="editais.Cronograma",
                    ),
                ),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cronogramas_selecao",
                        to="editais.Edital",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cronograma de Seleçao",
                "verbose_name_plural": "Cronogramas",
            },
            bases=("editais.cronograma",),
        ),
        migrations.AddField(
            model_name="documento",
            name="edital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos",
                to="editais.Edital",
            ),
        ),
    ]
