# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("editais", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edital",
            name="palavra_chave",
            field=models.ForeignKey(
                help_text="Palavra-chave para relacionar com as notícias referentes a esse edital.",
                on_delete=django.db.models.deletion.CASCADE,
                to="noticias.PalavrasChave",
                verbose_name="Palavra-chave",
            ),
        ),
    ]
