# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-13 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editais", "0003_cronograma_inscricao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cronograma",
            options={
                "ordering": ["inicio", "fim"],
                "verbose_name": "Cronograma",
                "verbose_name_plural": "Cronogramas",
            },
        ),
    ]
