# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-16 18:01
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editais", "0004_auto_20161013_1651"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edital",
            name="descricao",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Descrição"
            ),
        ),
    ]
