# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editais", "0005_auto_20161216_1801"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodoconvocacao",
            name="gerenciavel",
            field=models.BooleanField(
                default=False,
                help_text="Assinale essa opção caso deseje que o sistema gerencie a fase",
                verbose_name="Gerenciar via Portal",
            ),
            preserve_default=False,
        ),
    ]
