# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("editais", "0007_auto_20170217_1538"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edital",
            name="retificado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retificacoes",
                to="editais.Edital",
                verbose_name="Edital Retificado",
            ),
        ),
    ]
