# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import editais.validators


class Migration(migrations.Migration):

    dependencies = [
        ("editais", "0009_documento_atualizado_em"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="link_arquivo_externo",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL de arquivo externo"
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="arquivo",
            field=models.FileField(
                blank=True,
                help_text="Será aceito arquivo com tamanho máximo 2MB e que seja do tipo: pdf.",
                null=True,
                upload_to="",
                validators=[
                    editais.validators.FileValidator(
                        allowed_extensions=["pdf"], max_size=2097152
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="atualizado_em",
            field=models.DateField(auto_now=True, verbose_name="Data de atualização"),
        ),
    ]
