# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-21 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editais", "0010_auto_20170817_1401"),
    ]

    operations = [
        migrations.AddField(
            model_name="edital",
            name="url_video_descricao",
            field=models.URLField(
                blank=True,
                help_text='Copiar o endereço "src" que aparece na opção de compartilhamento "Incorporar" do YouTube.',
                null=True,
                verbose_name="URL de vídeo descritivo do edital",
            ),
        ),
    ]
