# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        max_length=36, unique=True, verbose_name="Task ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Aguardando"),
                            ("RECEIVED", "Recebida"),
                            ("STARTED", "Iniciada"),
                            ("SUCCESS", "Executada com sucesso"),
                            ("FAILURE", "Falha"),
                            ("REVOKED", "Cancelada"),
                            ("RETRY", "Aguardando nova tentativa"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de término"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "ordering": ("-start_time",),
            },
        ),
    ]
