# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("noticias", "0001_initial"),
        ("processoseletivo", "0001_initial"),
        ("cursos", "0001_initial"),
        ("editais", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchCursoEAD",
            fields=[],
            options={"proxy": True,},
            bases=("cursos.cursoead",),
        ),
        migrations.CreateModel(
            name="SearchCursoPresencial",
            fields=[],
            options={"proxy": True,},
            bases=("cursos.cursopresencial",),
        ),
        migrations.CreateModel(
            name="SearchEdital",
            fields=[],
            options={"proxy": True,},
            bases=("editais.edital",),
        ),
        migrations.CreateModel(
            name="SearchNoticia",
            fields=[],
            options={"proxy": True,},
            bases=("noticias.noticia",),
        ),
        migrations.CreateModel(
            name="SearchProcessoSeletivo",
            fields=[],
            options={"proxy": True,},
            bases=("processoseletivo.processoseletivo",),
        ),
    ]
