# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0010_auto_20160722_1002"),
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="SearchCursoEAD",),
        migrations.DeleteModel(name="SearchCursoPresencial",),
        migrations.CreateModel(
            name="SearchCurso",
            fields=[],
            options={"proxy": True,},
            bases=("cursos.cursonocampus",),
        ),
    ]
