# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-30 16:29
from __future__ import unicode_literals

import base.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0002_auto_20160809_1002"),
    ]

    operations = [
        migrations.CreateModel(
            name="PessoaFisica",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[base.validators.cpf_validator],
                        verbose_name="CPF",
                    ),
                ),
                (
                    "rg",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="RG"
                    ),
                ),
                (
                    "orgao_expeditor",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Orgão Expeditor",
                    ),
                ),
                (
                    "data_expedicao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Expedição"
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("nascimento", models.DateTimeField(verbose_name="Data de Nascimento")),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Feminino")],
                        max_length=1,
                        null=True,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "nome_mae",
                    models.CharField(max_length=100, verbose_name="Nome da Mãe"),
                ),
                (
                    "logradouro",
                    models.CharField(max_length=255, verbose_name="Logradouro"),
                ),
                (
                    "numero_endereco",
                    models.CharField(max_length=10, verbose_name="Número"),
                ),
                (
                    "complemento_endereco",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
                (
                    "uf",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapa"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantis"),
                        ],
                        max_length=2,
                        verbose_name="UF",
                    ),
                ),
                (
                    "municipio",
                    models.CharField(max_length=100, verbose_name="Município"),
                ),
                ("bairro", models.CharField(max_length=100, verbose_name="Bairro")),
                (
                    "cep",
                    models.CharField(
                        max_length=10,
                        validators=[base.validators.cep_validator],
                        verbose_name="CEP",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[base.validators.telefone_validator],
                        verbose_name="Celular",
                    ),
                ),
                (
                    "telefone2",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[base.validators.telefone_validator],
                        verbose_name="Telefone Fixo",
                    ),
                ),
                ("email", models.EmailField(max_length=55, verbose_name="E-mail")),
                (
                    "nacionalidade",
                    models.CharField(max_length=55, verbose_name="Nacionalidade"),
                ),
                (
                    "naturalidade",
                    models.CharField(max_length=55, verbose_name="Naturalidade"),
                ),
                (
                    "naturalidade_uf",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapa"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantis"),
                        ],
                        max_length=2,
                        verbose_name="UF da Naturalidade",
                    ),
                ),
                (
                    "profissao",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Profissão/Ocupação",
                    ),
                ),
                (
                    "tipo_sanguineo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A_POS", "A+"),
                            ("B_POS", "B+"),
                            ("AB_POS", "AB+"),
                            ("O_POS", "O+"),
                            ("A_NEG", "A-"),
                            ("B_NEG", "B-"),
                            ("AB_NEG", "AB-"),
                            ("O_NEG", "O-"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Tipo Sanguíneo",
                    ),
                ),
                (
                    "certidao",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Certidão de Nascimento",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pessoa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pessoa Física",
                "verbose_name_plural": "Pessoas Físicas",
            },
        ),
    ]
