# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 16:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_auto_20161018_1527"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoafisica",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pessoa",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
