# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    def alterar_nacionalidade(apps, schema_editor):
        pessoafisica_class = apps.get_model("base.PessoaFisica")
        pessoafisica_class.objects.exclude(nacionalidade="").update(
            nacionalidade_old=models.F("nacionalidade")
        )

        pessoafisica_class.objects.filter(
            models.Q(nacionalidade__icontains="Bra")
            | models.Q(nacionalidade__icontains="sileir")
            | models.Q(nacionalidade__icontains="pessoa")
            | models.Q(nacionalidade__icontains="campin")
            | models.Q(nacionalidade__icontains="paraí")
            | models.Q(nacionalidade__icontains="cabedel")
            | models.Q(nacionalidade__icontains="santa")
            | models.Q(nacionalidade__icontains="são")
            | models.Q(nacionalidade__icontains="cajazeir")
            | models.Q(nacionalidade__icontains="sousa")
            | models.Q(nacionalidade__icontains="patos")
            | models.Q(nacionalidade__icontains="guarabir")
            | models.Q(nacionalidade__icontains="pb")
        ).update(nacionalidade="BRASILEIRA")

        pessoafisica_class.objects.filter(
            models.Q(nacionalidade__icontains="ANGOLANA")
            | models.Q(nacionalidade="Argentina")
            | models.Q(nacionalidade="Colombiana")
            | models.Q(nacionalidade="Equatoriana")
            | models.Q(nacionalidade="Filipino")
            | models.Q(nacionalidade="Guineense")
            | models.Q(nacionalidade="Guiné-Bissau")
            | models.Q(nacionalidade="ITALIANO")
            | models.Q(nacionalidade="Iraquiana")
            | models.Q(nacionalidade__icontains="PORTUGUESA")
        ).update(nacionalidade="ESTRANGEIRA")

    def desfazer_alterar_nacionalidade(apps, schema_editor):
        pessoafisica_class = apps.get_model("base.PessoaFisica")
        pessoafisica_class.objects.exclude(nacionalidade_old="").update(
            nacionalidade=models.F("nacionalidade_old")
        )

    dependencies = [
        ("base", "0007_auto_20170727_1208"),
    ]

    operations = [
        migrations.RunPython(alterar_nacionalidade, desfazer_alterar_nacionalidade)
    ]
