# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_auto_20170727_1655"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoafisica",
            name="tipo_sanguineo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A_POS", "A+"),
                    ("B_POS", "B+"),
                    ("AB_POS", "AB+"),
                    ("O_POS", "O+"),
                    ("A_NEG", "A-"),
                    ("B_NEG", "B-"),
                    ("AB_NEG", "AB-"),
                    ("O_NEG", "O-"),
                    ("DESCONHECE", "Desconhecido"),
                ],
                max_length=10,
                null=True,
                verbose_name="Tipo Sanguíneo",
            ),
        ),
    ]
