# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 17:21
from __future__ import unicode_literals

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_auto_20170801_2108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoafisica",
            name="nome",
            field=models.CharField(
                max_length=100,
                validators=[base.validators.nome_de_pessoa_validator],
                verbose_name="Nome",
            ),
        ),
        migrations.AlterField(
            model_name="pessoafisica",
            name="nome_responsavel",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[base.validators.nome_de_pessoa_validator],
                verbose_name="Nome do Responsável",
            ),
        ),
    ]
