# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 10:39
from __future__ import unicode_literals

import base.history
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("noticias", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnaliseDocumental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "servidor_coordenacao",
                    models.CharField(
                        max_length=255, verbose_name="Servidor Responsável"
                    ),
                ),
                (
                    "observacao",
                    models.TextField(max_length=255, verbose_name="Observações finais"),
                ),
                ("data", models.DateField(verbose_name="Data da avaliação final")),
                (
                    "situacao_final",
                    models.BooleanField(
                        choices=[(True, "Deferido"), (False, "Indeferido")],
                        verbose_name="Situação final",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análise Documento",
                "verbose_name_plural": "Análise Documentos",
            },
        ),
        migrations.CreateModel(
            name="AvaliacaoDocumental",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "servidor_setor",
                    models.CharField(max_length=255, verbose_name="Avaliador"),
                ),
                ("data", models.DateField(verbose_name="Data da avaliação final")),
                (
                    "observacao",
                    models.TextField(max_length=255, verbose_name="Observação"),
                ),
                (
                    "situacao",
                    models.BooleanField(
                        choices=[(True, "Deferido"), (False, "Indeferido")],
                        verbose_name="Situação",
                    ),
                ),
                (
                    "analise_documental",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analise_documental",
                        to="processoseletivo.AnaliseDocumental",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação Documental",
                "verbose_name_plural": "Avaliações Documentais",
            },
        ),
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=55, unique=True)),
                ("sigla", models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={"verbose_name_plural": "Campi",},
        ),
        migrations.CreateModel(
            name="Candidato",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(max_length=11, unique=True, verbose_name="CPF"),
                ),
                (
                    "rg",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="RG"
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("nascimento", models.DateTimeField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")], max_length=1
                    ),
                ),
                ("nome_mae", models.CharField(max_length=100)),
                ("logradouro", models.CharField(max_length=255)),
                (
                    "numero_endereco",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("complemento_endereco", models.CharField(max_length=255)),
                ("uf", models.CharField(max_length=2, verbose_name="UF")),
                ("municipio", models.CharField(max_length=55)),
                ("bairro", models.CharField(max_length=55)),
                ("cep", models.CharField(max_length=9, verbose_name="CEP")),
                ("telefone", models.CharField(blank=True, max_length=15, null=True)),
                ("telefone2", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.CharField(max_length=55)),
            ],
            options={"ordering": ("nome",),},
        ),
        migrations.CreateModel(
            name="Chamada",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(auto_now_add=True)),
                (
                    "multiplicador",
                    models.IntegerField(verbose_name="Quantidade de convocações"),
                ),
                ("vagas", models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChamadaAdmin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processoseletivo.Campus",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrador de Chamadas",
                "verbose_name_plural": "Administradores de chamadas",
            },
        ),
        migrations.CreateModel(
            name="ConfirmacaoInteresse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Confirmação de Interesse",
                "verbose_name_plural": "Confirmações de Interesse",
            },
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.IntegerField(unique=True)),
                ("nome", models.CharField(max_length=55)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cursos",
                        to="processoseletivo.Campus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Desempenho",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota_em_linguas",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Nota em Línguas"
                    ),
                ),
                (
                    "nota_em_humanas",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Nota em Ciências Humanas",
                    ),
                ),
                (
                    "nota_em_ciencias_naturais",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Nota em Ciências Naturais",
                    ),
                ),
                (
                    "nota_em_matematica",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Nota em matemática",
                    ),
                ),
                (
                    "nota_na_redacao",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Nota na redação"
                    ),
                ),
                (
                    "nota_geral",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Nota final"
                    ),
                ),
                ("classificacao", models.IntegerField()),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desempenhos",
                        to="processoseletivo.Candidato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Edicao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField()),
                ("serial", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ABERTO", "ABERTO"), ("FECHADO", "FECHADO")],
                        max_length=55,
                    ),
                ),
                ("arquivo_csv", models.FileField(blank=True, null=True, upload_to="")),
                ("importado", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Edição",
                "verbose_name_plural": "Edições de Processos Seletivos",
            },
        ),
        migrations.CreateModel(
            name="EmailNotificacaoConvocados",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assunto", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CONVOCACAO", "Convocação"),
                            ("RESULTADO_PARCIAL", "Resultado Parcial"),
                            ("RESULTADO_FINAL", "Resultado Final"),
                        ],
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("mensagem", models.TextField()),
            ],
            options={
                "verbose_name": "Modelo de notificação aos convocados",
                "verbose_name_plural": "Configuração de notificação dos convocados",
            },
        ),
        migrations.CreateModel(
            name="Etapa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                (
                    "multiplicador",
                    models.IntegerField(verbose_name="Número de convocados"),
                ),
                (
                    "publica",
                    models.BooleanField(default=False, verbose_name="Publicar chamada"),
                ),
                ("encerrada", models.BooleanField(default=False)),
                (
                    "edicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processoseletivo.Edicao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=55, unique=True)),
            ],
            options={"verbose_name": "Formação", "verbose_name_plural": "Formações",},
        ),
        migrations.CreateModel(
            name="IES",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.IntegerField(unique=True)),
                ("nome", models.CharField(max_length=255, unique=True)),
                ("sigla", models.CharField(max_length=10, unique=True)),
                ("uf", models.CharField(max_length=2, verbose_name="UF")),
            ],
            options={
                "verbose_name": "Instituição de Ensino",
                "verbose_name_plural": "Instituições de Ensino",
            },
        ),
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chamada", models.BooleanField(default=False)),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscricoes",
                        to="processoseletivo.Candidato",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processoseletivo.Curso",
                    ),
                ),
                (
                    "edicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processoseletivo.Edicao",
                    ),
                ),
            ],
            options={"verbose_name": "Inscrição", "verbose_name_plural": "Inscrições",},
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matricula",
                        to="processoseletivo.Candidato",
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processoseletivo.Etapa",
                    ),
                ),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processoseletivo.Inscricao",
                    ),
                ),
            ],
            options={"verbose_name": "Matrícula", "verbose_name_plural": "Matrículas",},
        ),
        migrations.CreateModel(
            name="Modalidade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, unique=True)),
                ("resumo", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessoSeletivo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                ("sigla", models.CharField(max_length=15, verbose_name="Sigla")),
                (
                    "descricao",
                    models.TextField(max_length=1024, verbose_name="Descrição"),
                ),
                ("imagem", models.ImageField(upload_to="")),
                (
                    "palavra_chave",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="noticias.PalavrasChave",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processo Seletivo",
                "verbose_name_plural": "Processos Seletivos",
            },
            bases=(models.Model, base.history.HistoryMixin),
        ),
        migrations.CreateModel(
            name="Recurso",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "protocolo",
                    models.CharField(max_length=255, verbose_name="Protocolo"),
                ),
                (
                    "justificativa",
                    models.TextField(max_length=1000, verbose_name="Justificativa"),
                ),
                (
                    "status_recurso",
                    models.CharField(
                        choices=[
                            ("DEFERIDO", "DEFERIDO"),
                            ("INDEFERIDO", "INDEFERIDO"),
                        ],
                        max_length=10,
                        verbose_name="Status do recurso",
                    ),
                ),
                (
                    "analise_documental",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processoseletivo.AnaliseDocumental",
                    ),
                ),
            ],
            options={"verbose_name": "Recurso", "verbose_name_plural": "Recursos",},
        ),
        migrations.CreateModel(
            name="RegistroTransicaoModalidadeVagas",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destino_em_transacoes",
                        to="processoseletivo.Modalidade",
                    ),
                ),
                (
                    "origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origem_em_transacoes",
                        to="processoseletivo.Modalidade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resultado",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DEFERIDO", "DEFERIDO"),
                            ("INDEFERIDO", "INDEFERIDO"),
                            ("EXCEDENTE", "EXCEDENTE"),
                        ],
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("observacao", models.CharField(max_length=255, verbose_name="obs")),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processoseletivo.Candidato",
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processoseletivo.Etapa",
                    ),
                ),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processoseletivo.Inscricao",
                    ),
                ),
            ],
            options={"verbose_name": "Resultado", "verbose_name_plural": "Resultados",},
        ),
        migrations.CreateModel(
            name="TipoAnalise",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Tipo de Avalição"
                    ),
                ),
                (
                    "setor_responsavel",
                    models.CharField(max_length=255, verbose_name="Setor Responsável"),
                ),
                (
                    "descricao",
                    models.TextField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "modalidade",
                    models.ManyToManyField(
                        related_name="modalidade", to="processoseletivo.Modalidade"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo análise de documento",
                "verbose_name_plural": "Tipo análise de documentos",
            },
        ),
        migrations.CreateModel(
            name="TransicaoModalidade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modalidade_inicial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processoseletivo.Modalidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transição de modalidade",
                "verbose_name_plural": "Transições de modalidade",
            },
        ),
        migrations.CreateModel(
            name="TransicaoModalidadePossivel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transicao_destino",
                        to="processoseletivo.Modalidade",
                    ),
                ),
                (
                    "modalidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processoseletivo.TransicaoModalidade",
                    ),
                ),
                (
                    "origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transicao_origem",
                        to="processoseletivo.Modalidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transição de modalidade possível",
                "verbose_name_plural": "Transições de modalidade possíveis",
            },
        ),
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=55, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vaga",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processoseletivo.Candidato",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vagas",
                        to="processoseletivo.Curso",
                    ),
                ),
                (
                    "edicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vagas",
                        to="processoseletivo.Edicao",
                    ),
                ),
                (
                    "modalidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vagas",
                        to="processoseletivo.Modalidade",
                    ),
                ),
                (
                    "modalidade_primaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vagas_originais",
                        to="processoseletivo.Modalidade",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="registrotransicaomodalidadevagas",
            name="vaga",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transicoes",
                to="processoseletivo.Vaga",
            ),
        ),
        migrations.AddField(
            model_name="inscricao",
            name="modalidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="processoseletivo.Modalidade",
            ),
        ),
        migrations.AddField(
            model_name="edicao",
            name="processo_seletivo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edicoes",
                to="processoseletivo.ProcessoSeletivo",
            ),
        ),
        migrations.AddField(
            model_name="desempenho",
            name="edicao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="desempenhos",
                to="processoseletivo.Edicao",
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="formacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="processoseletivo.Formacao",
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="turno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="processoseletivo.Turno"
            ),
        ),
        migrations.AddField(
            model_name="confirmacaointeresse",
            name="etapa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="confirmacoes_interesse",
                to="processoseletivo.Etapa",
            ),
        ),
        migrations.AddField(
            model_name="confirmacaointeresse",
            name="inscricao",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="processoseletivo.Inscricao",
            ),
        ),
        migrations.AddField(
            model_name="chamada",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="processoseletivo.Curso"
            ),
        ),
        migrations.AddField(
            model_name="chamada",
            name="etapa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chamadas",
                to="processoseletivo.Etapa",
            ),
        ),
        migrations.AddField(
            model_name="chamada",
            name="modalidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="processoseletivo.Modalidade",
            ),
        ),
        migrations.AddField(
            model_name="candidato",
            name="chamadas",
            field=models.ManyToManyField(
                related_name="candidatos", to="processoseletivo.Chamada"
            ),
        ),
        migrations.AddField(
            model_name="candidato",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campus",
            name="ies",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campi",
                to="processoseletivo.IES",
                verbose_name="Instituição de Ensino",
            ),
        ),
        migrations.AddField(
            model_name="avaliacaodocumental",
            name="tipo_analise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tipo_analise",
                to="processoseletivo.TipoAnalise",
            ),
        ),
        migrations.AddField(
            model_name="analisedocumental",
            name="confirmacao_interesse",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="processoseletivo.ConfirmacaoInteresse",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="etapa", unique_together=set([("edicao", "numero")]),
        ),
        migrations.AlterUniqueTogether(
            name="edicao",
            unique_together=set([("processo_seletivo", "ano", "serial")]),
        ),
        migrations.AlterUniqueTogether(
            name="avaliacaodocumental",
            unique_together=set([("tipo_analise", "analise_documental")]),
        ),
    ]
