# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ("processoseletivo", "0002_auto_20160321_1816"),
    ]

    operations = [
        migrations.AddField(
            model_name="processoseletivo",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "imagem",
                "200x100",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="cropping",
            ),
        ),
        migrations.AlterField(
            model_name="processoseletivo",
            name="imagem",
            field=models.ImageField(
                help_text="Ao concluir o preenchimento do formulário, clique em 'Salvar e continuar editando' para personalizar o tamanho da imagem. ",
                upload_to="",
            ),
        ),
    ]
