# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-30 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processoseletivo", "0003_auto_20160401_1721"),
    ]

    operations = [
        migrations.AddField(
            model_name="edicao",
            name="nome",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="edicao",
            name="serial",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name="edicao", old_name="serial", new_name="semestre",
        ),
        migrations.AlterUniqueTogether(name="edicao", unique_together=set([]),),
    ]
