# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-09 10:54
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_candidatos(apps, schema_editor):
    pessoa_class = apps.get_model("base", "pessoafisica")
    candidato_class = apps.get_model("processoseletivo", "candidato")
    for c in candidato_class.objects.all():
        pessoa = pessoa_class.objects.get(user__username=c.cpf)
        c.pessoa = pessoa
        c.save()


def reverse_migrate_candidatos(apps, schema_editor):
    candidato_class = apps.get_model("processoseletivo", "candidato")
    candidato_class.objects.all().update(pessoa=None)


def adicionar_inscricao(apps, schema_editor):
    desempenho_class = apps.get_model("processoseletivo", "desempenho")
    curso_class = apps.get_model("processoseletivo", "curso")
    curso_class.objects.filter(codigo=372).delete()
    curso_class.objects.filter(codigo=-372).update(codigo=372)

    for d in desempenho_class.objects.all():
        inscricoes = d.candidato.inscricoes.filter(edicao=d.edicao)
        cursos = len(set([i.curso for i in inscricoes]))
        assert cursos == 1
        d.inscricao = inscricoes.first()
        d.save()


def remover_inscricao(apps, schema_editor):
    desempenho_class = apps.get_model("processoseletivo", "desempenho")
    desempenho_class.objects.all().update(inscricao=None)


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_auto_20161018_1527"),
        ("processoseletivo", "0004_auto_20160930_1629"),
    ]

    operations = [
        migrations.AddField(
            model_name="edicao",
            name="arquivo_resultado_csv",
            field=models.FileField(
                blank=True,
                help_text="Arquivo CSV com o resultado",
                null=True,
                upload_to="processoseletivo/edicoes/csvs/",
                verbose_name="Resultado",
            ),
        ),
        migrations.AlterField(
            model_name="edicao",
            name="arquivo_csv",
            field=models.FileField(
                blank=True,
                help_text="Arquivo CSV com a lista de espera",
                null=True,
                upload_to="processoseletivo/edicoes/csvs/",
                verbose_name="Lista de espera",
            ),
        ),
        migrations.RenameField(
            model_name="edicao",
            old_name="arquivo_csv",
            new_name="arquivo_lista_espera_csv",
        ),
        migrations.AlterModelOptions(
            name="candidato", options={"ordering": ("pessoa__nome",)},
        ),
        migrations.RemoveField(model_name="candidato", name="bairro",),
        migrations.RemoveField(model_name="candidato", name="cep",),
        migrations.RemoveField(model_name="candidato", name="complemento_endereco",),
        migrations.RemoveField(model_name="candidato", name="email",),
        migrations.RemoveField(model_name="candidato", name="logradouro",),
        migrations.RemoveField(model_name="candidato", name="municipio",),
        migrations.RemoveField(model_name="candidato", name="nascimento",),
        migrations.RemoveField(model_name="candidato", name="nome",),
        migrations.RemoveField(model_name="candidato", name="nome_mae",),
        migrations.RemoveField(model_name="candidato", name="numero_endereco",),
        migrations.RemoveField(model_name="candidato", name="rg",),
        migrations.RemoveField(model_name="candidato", name="sexo",),
        migrations.RemoveField(model_name="candidato", name="telefone",),
        migrations.RemoveField(model_name="candidato", name="telefone2",),
        migrations.RemoveField(model_name="candidato", name="uf",),
        migrations.RemoveField(model_name="candidato", name="user",),
        migrations.AddField(
            model_name="candidato",
            name="pessoa",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="candidato_ps",
                to="base.PessoaFisica",
                verbose_name="Pessoa Física",
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="cpf",
            field=models.CharField(max_length=14, unique=True, verbose_name="CPF"),
        ),
        migrations.RunPython(migrate_candidatos, reverse_migrate_candidatos),
        migrations.CreateModel(
            name="ModalidadeVariavel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, unique=True)),
                (
                    "modalidade",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        to="processoseletivo.Modalidade",
                        verbose_name="Modalidade primária",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="desempenho",
            name="inscricao",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                to="processoseletivo.Inscricao",
                verbose_name="Inscrição",
            ),
        ),
        migrations.RunPython(adicionar_inscricao, remover_inscricao),
        migrations.RemoveField(model_name="candidato", name="cpf",),
        migrations.AlterField(
            model_name="candidato",
            name="pessoa",
            field=models.OneToOneField(
                on_delete=models.deletion.PROTECT,
                related_name="candidato_ps",
                to="base.PessoaFisica",
                verbose_name="Pessoa Física",
            ),
        ),
        migrations.RemoveField(model_name="desempenho", name="candidato",),
        migrations.RemoveField(model_name="desempenho", name="edicao",),
        migrations.AlterField(
            model_name="desempenho",
            name="inscricao",
            field=models.OneToOneField(
                on_delete=models.deletion.CASCADE,
                to="processoseletivo.Inscricao",
                verbose_name="Inscrição",
            ),
        ),
    ]
