# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-17 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processoseletivo", "0006_curso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chamada",
            name="curso2",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE, to="cursos.CursoNoCampus"
            ),
        ),
        migrations.AlterField(
            model_name="inscricao",
            name="curso2",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="inscricoes_mec",
                to="cursos.CursoNoCampus",
            ),
        ),
        migrations.AlterField(
            model_name="vaga",
            name="curso2",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE, to="cursos.CursoNoCampus"
            ),
        ),
        migrations.RenameField(
            model_name="chamada", old_name="curso", new_name="curso_velho",
        ),
        migrations.RenameField(
            model_name="chamada", old_name="curso2", new_name="curso",
        ),
        migrations.RemoveField(model_name="chamada", name="curso_velho",),
        migrations.RenameField(
            model_name="inscricao", old_name="curso", new_name="curso_velho",
        ),
        migrations.RenameField(
            model_name="inscricao", old_name="curso2", new_name="curso",
        ),
        migrations.RemoveField(model_name="inscricao", name="curso_velho",),
        migrations.RenameField(
            model_name="vaga", old_name="curso", new_name="curso_velho",
        ),
        migrations.RenameField(model_name="vaga", old_name="curso2", new_name="curso",),
        migrations.RemoveField(model_name="vaga", name="curso_velho",),
        migrations.RemoveField(model_name="campus", name="ies",),
        migrations.RemoveField(model_name="chamadaadmin", name="campus",),
        migrations.RemoveField(model_name="chamadaadmin", name="user",),
        migrations.RemoveField(model_name="curso", name="campus",),
        migrations.RemoveField(model_name="curso", name="formacao",),
        migrations.RemoveField(model_name="curso", name="turno",),
        migrations.DeleteModel(name="Campus",),
        migrations.DeleteModel(name="ChamadaAdmin",),
        migrations.DeleteModel(name="Curso",),
        migrations.DeleteModel(name="Formacao",),
        migrations.DeleteModel(name="IES",),
        migrations.DeleteModel(name="Turno",),
        migrations.DeleteModel(name="EmailNotificacaoConvocados",),
    ]
