# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 16:25
from __future__ import unicode_literals

from django.db import migrations


def adicionar_inscricoes(apps, schema_editor):
    chamada_class = apps.get_model("processoseletivo", "chamada")
    inscricao_class = apps.get_model("processoseletivo", "inscricao")
    etapa_class = apps.get_model("processoseletivo", "etapa")
    for c in chamada_class.objects.all():
        inscricao_class.objects.filter(
            curso=c.curso,
            modalidade=c.modalidade,
            edicao=c.etapa.edicao,
            candidato__in=c.candidatos.all(),
        ).update(chamada=c)
        assert c.candidatos.count() == c.inscricoes.count()


def remover_inscricoes(apps, schema_editor):
    inscricao_class = apps.get_model("processoseletivo", "inscricao")
    inscricao_class.objects.all().update(chamada=None)


class Migration(migrations.Migration):

    dependencies = [
        ("processoseletivo", "0009_auto_20170131_1619"),
    ]

    operations = [
        migrations.RunPython(adicionar_inscricoes, remover_inscricoes),
        migrations.RemoveField(model_name="candidato", name="chamadas",),
        migrations.RemoveField(model_name="matricula", name="candidato",),
        migrations.RemoveField(model_name="resultado", name="candidato",),
    ]
