# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("processoseletivo", "0010_inscricoes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroVagas",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros",
                        to="processoseletivo.Candidato",
                        verbose_name="Candidato",
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registro_vagas",
                        to="processoseletivo.Etapa",
                        verbose_name="Etapa",
                    ),
                ),
                (
                    "modalidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processoseletivo.Modalidade",
                        verbose_name="Modalidade de cota",
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros",
                        to="processoseletivo.Vaga",
                        verbose_name="Vaga",
                    ),
                ),
            ],
        ),
    ]
