# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("processoseletivo", "0011_registrovagas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscricao",
            name="chamada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inscricoes",
                to="processoseletivo.Chamada",
                verbose_name="Chamada",
            ),
        ),
        migrations.RemoveField(model_name="registrovagas", name="candidato",),
        migrations.RemoveField(model_name="registrovagas", name="etapa",),
        migrations.RemoveField(model_name="registrovagas", name="modalidade",),
        migrations.RemoveField(model_name="registrovagas", name="vaga",),
        migrations.DeleteModel(name="RegistroVagas",),
    ]
