# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("processoseletivo", "0012_auto_20170217_1550"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etapa",
            name="multiplicador",
            field=models.IntegerField(
                help_text="Quantidade de candidatos convocados por cada vaga remanescente",
                verbose_name="Número de convocados",
            ),
        ),
        migrations.AlterField(
            model_name="processoseletivo",
            name="palavra_chave",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="noticias.PalavrasChave",
            ),
        ),
    ]
