# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("processoseletivo", "0013_auto_20170418_0949"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etapa",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cursos.Campus",
                verbose_name="Campus",
            ),
        ),
    ]
