# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("processoseletivo", "0014_auto_20170420_1134"),
        ("processoseletivo", "0014_auto_20170419_1339"),
    ]

    operations = []
