# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("processoseletivo", "0015_merge_20170420_1602"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processoseletivo",
            options={
                "ordering": ["sigla"],
                "verbose_name": "Processo Seletivo",
                "verbose_name_plural": "Processos Seletivos",
            },
        ),
    ]
