# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processoseletivo", "0016_auto_20170426_1029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipoanalise",
            name="descricao",
            field=models.TextField(max_length=1500, verbose_name="Descrição"),
        ),
    ]
