# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-02 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("processoseletivo", "0019_auto_20170918_1622"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="edicao",
            options={
                "ordering": ("processo_seletivo", "-ano", "-semestre", "nome"),
                "verbose_name": "Edição",
                "verbose_name_plural": "Edições de Processos Seletivos",
            },
        ),
        migrations.AlterModelOptions(
            name="etapa",
            options={
                "ordering": (
                    "-edicao__ano",
                    "-edicao__semestre",
                    "edicao__nome",
                    "-numero",
                    "campus",
                )
            },
        ),
        migrations.AlterField(
            model_name="etapa",
            name="edicao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="processoseletivo.Edicao",
                verbose_name="Edição",
            ),
        ),
        migrations.AlterField(
            model_name="etapa",
            name="numero",
            field=models.IntegerField(verbose_name="Número da Etapa"),
        ),
    ]
