# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-20 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("processoseletivo", "0020_auto_20180202_1703"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="edicao",
            options={
                "verbose_name": "Edição",
                "verbose_name_plural": "Edições de Processos Seletivos",
            },
        ),
        migrations.AlterModelOptions(name="etapa", options={},),
    ]
