# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-22 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processoseletivo", "0021_auto_20180220_1522"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurso",
            name="justificativa",
            field=models.TextField(max_length=500, verbose_name="Justificativa"),
        ),
        migrations.AlterField(
            model_name="resultado",
            name="observacao",
            field=models.CharField(max_length=525, verbose_name="Observação"),
        ),
        migrations.AlterField(
            model_name="resultado",
            name="status",
            field=models.CharField(
                choices=[
                    ("DEFERIDO", "DEFERIDO"),
                    ("INDEFERIDO", "INDEFERIDO"),
                    ("EXCEDENTE", "EXCEDENTE"),
                ],
                max_length=10,
                verbose_name="Situação",
            ),
        ),
    ]
