# Generated by Django 2.2.12 on 2020-07-15 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("processoseletivo", "0023_auto_20190226_1035"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chamada",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cursos.CursoSelecao"
            ),
        ),
        migrations.AlterField(
            model_name="inscricao",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inscricoes_mec",
                to="cursos.CursoSelecao",
            ),
        ),
        migrations.AlterField(
            model_name="vaga",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cursos.CursoSelecao"
            ),
        ),
    ]
