# Generated by Django 2.2.14 on 2020-12-02 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processoseletivo', '0024_auto_20200715_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidadevariavel',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processoseletivo.Modalidade', verbose_name='Modalidade de cota primária'),
        ),
    ]
