# Generated by Django 2.2.14 on 2021-01-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processoseletivo', '0025_auto_20201202_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoseletivo',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
