from django.conf.urls import url
from django.urls import path
from processoseletivo import views
from processoseletivo.views import ProcessoPcd,ProcessoSistemRvCotas


urlpatterns = [
    url(r"^$", views.ProcessosIndexView.as_view(), name="indexprocessoseletivo"),
    url(
        r"^processo/(?P<processo_pk>[0-9]+)/$",
        views.ProcessosView.as_view(),
        name="processoseletivo",
    ),
    url(r"^duvidas", views.ProcessoDuvidas.as_view(), name="duvidas"),
    url(r"^cursos", views.ProcessoListaCursos.as_view(), name="lista_de_cursos"),
    url(r"^cronograma", views.ProcessoCronograma.as_view(), name="cronograma"),
    url(r"^sistema_rv_cotas", views.ProcessoSistemRvCotas.as_view(), name = "sistema_rv"),
    url(r"^documentos_inscricao",views.ProcessoDocumentos.as_view(), name="documentos_inscricao"),
    path("pcd", ProcessoPcd, name="pcd"),
    url(r"^concorrencia_integrado", views.ProcessoListaCursosIntegrado.as_view(), name="concorrencia_integrado"),
    url(r"^concorrencia_subsequent", views.ProcessoListaCursosSubsequente.as_view(), name="concorrencia_subsequente"),
    url(r"^concorrencia_concomitante", views.ProcessoListaCursosConcomitante.as_view(), name="concorrencia_concomitante"),
    url(
        r"^processo/(?P<processo_pk>[0-9]+)/edicoes/$",
        views.EdicoesView.as_view(),
        name="edicoes",
    ),
    url(
        r"^processo/(?P<processo_pk>[0-9]+)/edicao/(?P<edicao_pk>[0-9]+)/$",
        views.EdicaoView.as_view(),
        name="edicao",
    ),
    url(
        r"^edicao/(?P<edicao_pk>[0-9]+)/etapas/$",
        views.EtapasView.as_view(),
        name="etapas",
    ),
    url(
        r"^edicao/(?P<edicao_pk>[0-9]+)/etapa-resultado/$",
        views.EtapasResultadoView.as_view(),
        name="etapas_resultado",
    ),
    url(
        r"^edicao/(?P<edicao_pk>[0-9]+)/etapa/(?P<etapa_pk>[0-9]+)/$",
        views.CampusView.as_view(),
        name="edicao_etapa",
    ),
    url(
        r"^processo/(?P<processo_pk>[0-9]+)/etapas/$",
        views.EtapasView.as_view(),
        name="etapas_ps",
    ),
    url(
        r"^etapa/(?P<pk>[0-9]+)/campus/(?P<campus>[0-9]+)/$",
        views.CursosView.as_view(),
        name="cursos",
    ),
    url(
        r"^etapa/(?P<pk>[0-9]+)/campus/(?P<campus>[0-9]+)/curso/(?P<curso>[0-9]+)/$",
        views.ChamadaView.as_view(),
        name="chamadas",
    ),
    url(
        r"^importacao/(?P<pk>[0-9]+)/$",
        views.ImportacaoView.as_view(),
        name="importacao",
    ),
    url(
        r"^adicionar_chamadas/(?P<etapa_pk>[0-9]+)/$",
        views.CreateChamadaView.as_view(),
        name="adicionar_chamadas",
    ),
    url(
        r"^adicionar_candidatos/(?P<chamada_pk>[0-9]+)/$",
        views.AddCandidatosView.as_view(),
        name="adicionar_candidatos",
    ),
    url(
        r"^candidato/matricular/(?P<candidato_pk>[0-9]+)/(?P<modalidade_pk>[0-9]+)/(?P<etapa_pk>[0-9]+)/$",
        views.MatricularView.as_view(),
        name="matricular",
    ),
    url(
        r"^candidato/cancelar_matricula/(?P<candidato_pk>[0-9]+)/(?P<modalidade_pk>[0-9]+)/(?P<etapa_pk>[0-9]+)/$",
        views.CancelarMatriculaView.as_view(),
        name="cancelar_matricula",
    ),
    url(
        r"^candidato/confirmar_interesse/(?P<candidato_pk>[0-9]+)/(?P<modalidade_pk>[0-9]+)/(?P<etapa_pk>[0-9]+)/$",
        views.ConfirmarInteresseView.as_view(),
        name="confirmar_interesse",
    ),
    url(
        r"^candidato/cancelar_interesse/(?P<candidato_pk>[0-9]+)/(?P<modalidade_pk>[0-9]+)/(?P<etapa_pk>[0-9]+)/$",
        views.CancelarConfirmacaoView.as_view(),
        name="cancelar_interesse",
    ),
    url(
        r"^relatorio_convocados/(?P<etapa_pk>[0-9]+)/$",
        views.RelatorioConvocadosView.as_view(),
        name="relatorio_convocados",
    ),
    url(
        r"^etapa/(?P<etapa_pk>[0-9]+)/convocados-por-cota/$",
        views.RelatorioConvocadosPorCotaView.as_view(),
        name="relatorio-convocados-por-cota",
    ),
    url(
        r"^relatorio_matriculados/(?P<etapa_pk>[0-9]+)/$",
        views.RelatorioMatriculadosView.as_view(),
        name="relatorio_matriculados",
    ),
    url(
        r"^gerar_lista_analise_documental/(?P<etapa_pk>[0-9]+)/$",
        views.AnaliseDocumentoEtapaView.as_view(),
        name="gerar_lista_analise_documental",
    ),
    url(
        r"^gerar_listagem_final_deferidos/(?P<etapa_pk>[0-9]+)/$",
        views.ListagemFinalDeferidos.as_view(),
        name="gerar_listagem_final_deferidos",
    ),
    url(
        r"^gerar_listagem_final_indeferidos/(?P<etapa_pk>[0-9]+)/$",
        views.ListagemFinalIndeferidos.as_view(),
        name="gerar_listagem_final_indeferidos",
    ),
    url(
        r"^gerar_listagem_final_excedentes/(?P<etapa_pk>[0-9]+)/$",
        views.ListagemFinalExcedentes.as_view(),
        name="gerar_listagem_final_excedentes",
    ),
    url(
        r"^gerar_forms_analise_documento/(?P<chamada_pk>[0-9]+)/$",
        views.FormulariosAnaliseDocumentoView.as_view(),
        name="gerar_forms_analise_documento",
    ),
    url(r"^vagas/(?P<pk>[0-9]+)/$", views.VagasView.as_view(), name="vagas_ps"),
    url(
        r"^relatorio_resultado/(?P<pk>[0-9]+)/$",
        views.RelatorioResultadoView.as_view(),
        name="relatorio_resultado_ps",
    ),
    url(
        r"^encerrar_etapa/(?P<etapa_pk>[0-9]+)/$",
        views.EncerrarEtapalView.as_view(),
        name="encerrar_etapa",
    ),
    url(
        r"^reabrir_etapa/(?P<etapa_pk>[0-9]+)/$",
        views.ReabrirEtapalView.as_view(),
        name="reabrir_etapa",
    ),
    url(
        r"^replicar_analise_documental/(?P<analise_pk>[0-9]+)/$",
        views.ReplicarAnaliseDocumentalView.as_view(),
        name="replicar_analise_documental",
    ),
    url(
        r"^avaliacao_medica/$",
        views.AvaliacaoMedicaListView.as_view(),
        name="avaliacao_medica_changelist",
    ),
    url(
        r"^avaliacao_medica/inscricao/(?P<inscricao_pk>[0-9]+)/add/$",
        views.AvaliacaoMedicaCreateView.as_view(),
        name="avaliacao_medica_add",
    ),
    url(
        r"^avaliacao_medica/(?P<pk>[0-9]+)/$",
        views.AvaliacaoMedicaUpdateView.as_view(),
        name="avaliacao_medica_update",
    ),
    url(
        r"^avaliacao_medica/(?P<pk>[0-9]+)/delete/$",
        views.AvaliacaoMedicaDeleteView.as_view(),
        name="avaliacao_medica_delete",
    ),
    url(
        r"^avaliacao_medica/(?P<pk>[0-9]+)/detail/$",
        views.AvaliacaoMedicaDetailView.as_view(),
        name="avaliacao_medica_detail",
    ),
    url(r"^medico/$", views.MedicoListView.as_view(), name="medico_changelist"),
    url(r"^medico/add/$", views.MedicoUpdateView.as_view(), name="medico_add"),
    url(
        r"^medico/(?P<pk>[0-9]+)/change/$",
        views.MedicoUpdateView.as_view(),
        name="medico_change",
    ),
    url(
        r"^avaliacao_socioeconomica/$",
        views.AvaliacaoSocioeconomicaListView.as_view(),
        name="avaliacao_socioeconomica_changelist",
    ),
    url(
        r"^avaliacao_socioeconomica/inscricao/(?P<inscricao_pk>[0-9]+)/add/$",
        views.AvaliacaoSocioeconomicaCreateView.as_view(),
        name="avaliacao_socioeconomica_add",
    ),
    url(
        r"^avaliacao_socioeconomica/(?P<pk>[0-9]+)/$",
        views.AvaliacaoSocioeconomicaUpdateView.as_view(),
        name="avaliacao_socioeconomica_update",
    ),
    url(
        r"^avaliacao_socioeconomica/(?P<pk>[0-9]+)/delete/$",
        views.AvaliacaoSocioEconomicaDeleteView.as_view(),
        name="avaliacao_socioeconomica_delete",
    ),
    url(
        r"^avaliacao_socioeconomica/(?P<pk>[0-9]+)/detail/$",
        views.AvaliacaoSocioeconomicaDetailView.as_view(),
        name="avaliacao_socioeconomica_detail",
    ),
    url(r"^servidor_caest/$", views.CaestListView.as_view(), name="caest_changelist"),
    url(r"^servidor_caest/add/$", views.CaestUpdateView.as_view(), name="caest_add"),
    url(
        r"^servidor_caest/(?P<pk>[0-9]+)/change/$",
        views.CaestUpdateView.as_view(),
        name="caest_change",
    ),
    url(
        r"^avaliacao/(?P<pk>[0-9]+)/print/$",
        views.ImprimirAvaliacaoDocumentalView.as_view(),
        name="avaliacao_print",
    ),
    url(
        r"^autocomplete-candidato/$",
        views.AutoCompleteCandidato.as_view(),
        name="autocomplete_candidato",
    ),
    url(
        r"^autocomplete-inscricao/$",
        views.AutoCompleteInscricao.as_view(),
        name="autocomplete_inscricao",
    ),
    url(
        r"^autocomplete-confirmacao-interesse/$",
        views.AutoCompleteConfirmacaoInteresse.as_view(),
        name="autocomplete_confirmacao_interesse",
    ),
    url(
        r"^autocomplete-analise-documental/$",
        views.AutoCompleteAnaliseDocumental.as_view(),
        name="autocomplete_analise_documental",
    ),
]
